### ISSUE TITLE
Heart of Azeroth Level as P: Condition

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#101]
Some Quests require a certain level for your necklace , aka the heart of azeroth , to become available.
How would we do this in Grail? Not sure which api even exposes the heart level

**Comment by smaitch** [comment]
Perhaps the item link will have information in it.  I will have to check.

**Comment by yoshimo** [comment]
C_AzeriteItem.GetAzeriteItemXPInfo and related might work according to https://www.reddit.com/r/wow/comments/9829nh/macro_or_well_api_access_to_heart_of_azeroth_data/

**Comment by yoshimo** [comment]
/dump C_AzeriteItem.GetPowerLevel(C_AzeriteItem.FindActiveAzeriteItem())
returns 73, which is what we need.

**Comment by yoshimo** [comment]
An example quest would be https://www.wowhead.com/quest=56401/a-bolt-from-the-blue#comments

**Comment by smaitch** [comment]
This feature has been added to the next version of Grail.
