### ISSUE TITLE
PTR/Classic/Live 25.12.2019 SavedVar

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#102]
Unfortunately my 8.3 branch got eaten by a bad update, but the collected quests from 8.3 are still saved in this file
[Grail_PTR+Classic+Live_25.12.2019.zip](https://github.com/smaitch/Grail/files/4000241/Grail_PTR%2BClassic%2BLive_25.12.2019.zip)

The black empire campaign seems to start if you have unlocked the heartforge and entering the two bfa isles like boralus.
I will supply the conditions and proper Patchlevels for the first appearance of a quest with the next character copy.

**Comment by smaitch** [comment]
These were merged into the current master branch.
