### ISSUE TITLE
8.3 Quest API and ThreatQuests

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#106]
Still looking for what it does exactly but
https://wow.gamepedia.com/Patch_8.3.0/API_changes
mentions a few things that might be worth checking out:
```

    C_QuestLog.GetActiveThreatMaps
    C_QuestLog.HasActiveThreats
    C_QuestLog.IsThreatQuest
    C_TaskQuest.GetThreatQuests
```

> Dump: value=C_TaskQuest.GetThreatQuests()
> [1]={
>   [1]=55350,
>   [2]=56064,
>   [3]=56308,
>   [4]=57008,
>   [5]=57157,
>   [6]=57728
> }

**Comment by smaitch** [comment]
The next release of Grail records the currently available threat quests using this API.
