### ISSUE TITLE
Quest to change and information request

### ISSUE THREAD

**Issue by DreamOfHero** [smaitch/Grail#116]
Hi,

I found that:

Mission ID 1918 is only Horde quest: https://www.wowhead.com/quest=1918/the-befouled-element
Mission ID 9612 is only Draenei quest: https://www.wowhead.com/quest=9612/a-hearty-thanks

I changed already the file on folder, I have a question: 
in the comment of the Grail-Quests-_retail_.lua file, you wrote: "--		Rx			where x is the key to a permitted race (see raceMapping).  if no Rx is present any race can accept the quest"

where is raceMapping? I can't find it in any file.

Thank in advance
Kind regards
Andrea

**Comment by smaitch** [comment]
Hi.  The comment about raceMapping seems not to have been updated with the change in the Grail.lua file to use races instead.  As seen below Draenei would be D.

		races = {
			-- [1] is Blizzard API return (non-localized)
			-- [2] is localized male
			-- [3] is localized female
			-- [4] is bitmap value
			['A'] = { 'Pandaren', 'Pandaren',  'Pandaren',  0x08000000 },
			['B'] = { 'BloodElf', 'Blood Elf', 'Blood Elf', 0x02000000 },
			['C'] = { 'DarkIronDwarf', 'Dark Iron Dwarf', 'Dark Iron Dwarf', 0x00000004 },
			['D'] = { 'Draenei',  'Draenei',   'Draenei',   0x00080000 },
			['E'] = { 'NightElf', 'Night Elf', 'Night Elf', 0x00020000 },
			['F'] = { 'Dwarf',    'Dwarf',     'Dwarf',     0x00010000 },
			['G'] = { 'Goblin',   'Goblin',    'Goblin',    0x04000000 },
			['H'] = { 'Human',    'Human',     'Human',     0x00008000 },
			['I'] = { 'LightforgedDraenei', 'Lightforged Draenei', 'Lightforged Draenei', 0x40000000 },
			['J'] = { 'MagharOrc', "Mag'har Orc", "Mag'har Orc", 0x00000008 },
			['K'] = { 'KulTiran', "Kul'Tiran", "Kul'Tiran", 0x80000000 },
			['L'] = { 'Troll',    'Troll',     'Troll',     0x01000000 },
			['M'] = { 'HighmountainTauren', 'Highmountain Tauren', 'Highmountain Tauren', 0x00000001 },
			['N'] = { 'Gnome',    'Gnome',     'Gnome',     0x00040000 },
			['O'] = { 'Orc',      'Orc',       'Orc',       0x00200000 },
-- Do not ever use P because it will interfere with SP quest code
			['Q'] = { 'Mechagnome', 'Mechagnome', 'Mechagnome', 0x00002000 },
			['R'] = { 'Nightborne', 'Nightborne', 'Nightborne', 0x00000002 },
			['S'] = { 'Vulpera', 'Vulpera', 'Vulpera', 0x00004000 },
			['T'] = { 'Tauren',   'Tauren',    'Tauren',    0x00800000 },
			['U'] = { 'Scourge',  'Undead',    'Undead',    0x00400000 },
			['V'] = { 'VoidElf',  'Void Elf',  'Void Elf',	0x20000000 },
			['W'] = { 'Worgen',   'Worgen',    'Worgen',    0x00100000 },
			['Z'] = { 'ZandalariTroll', 'Zandalari Troll', 'Zandalari Troll', 0x10000000 },
			},

**Comment by DreamOfHero** [comment]
I Save it in in my Explaination File, Thanks.
*Andrea*

Il giorno dom 2 feb 2020 alle ore 00:01 Scott Harrison <
notifications@github.com> ha scritto:

**Comment by smaitch** [comment]
Both the quests you have mentioned seem to be properly marked in the latest version of Grail.
