### ISSUE TITLE
Classic - Holidays

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#117]
Yet another holiday is coming to an end, yet another incoming soon.
I realise that there is no adequate API for reading the calendar in Classic.

If Classic
  Read textile with list of start and stop dates
 Compare with current date/time
return current holiday(s)

Or something similar.

Thanks for your consideration.

**Comment by smaitch** [comment]
The next release of Grail has a few upcoming holidays determined assuming the dates from Retail are the same in Classic.

**Comment by Nerillida** [comment]
Thanks.
