### ISSUE TITLE
Classic - Darkmoon Faire

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#121]
Sorry to be a pain, but we need DMF handling as well as other holidays.

In fact, so that the NPCs are in the correct positions, we need 3 versions of the holiday.

One for the quests. Occurs wherever holiday is, and one for each location for NPCs and their aliases to alternate position.

Thanks

**Comment by Nerillida** [comment]
ADDITION: 

I had assumed that the H(holiday code) in an NPC's definition affected their visibility in lists/map pins.
Apparently not. 
So, I am unsure what can be done to show the correct location for the NPCs in the Classic version.

**Comment by smaitch** [comment]
The fact that holiday codes are associated with NPCs is from way back in time and I do not think has any real bearing on them now.
In any case, as long as we can create alias NPC locations and the quests can be marked with the proper alias values I think all should work for those NPCs who have different locations based on Darkmoon Faire presence.

**Comment by Nerillida** [comment]
Sure, it will work, and I have tested it with both
NPCs having two locations
NPCs having aliases at one location, original at the other.
When I "force" DMF as current, they appear at both locations. I had hoped for an indication of which was the current. 
I don't know how to do this, it may be that it's not worth while.
For now, my copy shows them in both places.

**Comment by smaitch** [comment]
I have updated Grail to handle knowing when Darkmoon Faire is present in Classic.

Do you have an example NPC that is showing in both locations at the moment?  I might be able to work on something.

**Comment by Nerillida** [comment]
G[14832]={'HF 1429:40.50,69.90 1412:37.80,39.80'} -- Kerri Hicks

regarding 

G[7889]='HF K0601 L001 N255 A:14832 T:14832 E31727' -- Coarse Weightstone

**Comment by Nerillida** [comment]
The quest above is not finished with, will need reputation "stuff".

**Comment by smaitch** [comment]
So I would suggest making a 14832 and a 514832 which would be the alias version.  Make each NPC in its own location.  Make sure the quest is associated with the proper NPC.  This should allow her map pin only to appear when the quest associated is available, and therefore when Darkmoon Faire is not up her map pin should not be there either.

**Comment by Nerillida** [comment]
It's the same quest number at each location. That's the problem. There are not separate quest numbers for Elwyn and Mulgore.

**Comment by smaitch** [comment]
But they are faction based, correct?  In this case you can use AP: codes, such as AP:14832:FA;514832:FH and a the same type of thing for the TP: code.  This code allows us to control which NPC is used based on prerequisite information (like faction, reputation level, etc.)

**Comment by Nerillida** [comment]
They're not faction based.

**Comment by Nerillida** [comment]
According to the historical web records.

**Comment by smaitch** [comment]
So if either faction can attend Darkmoon Faire in either location, and the same quest is used for both, then her map pin should appear in both places as one can get the quest in either place.  I would assume one can also turn it in to either place (even if different from where you got it).

**Comment by smaitch** [comment]
This same concept applies to all those people in the capital cities that give out the same quest.  They can have pins in each city at the same time.

**Comment by Nerillida** [comment]
Yes, although a lot are SP, as I remember, but, the only difference is WHEN then quests are available. 
The characters in the city are not duplicated. They each announce their respective occurrence of the faire, AFAIK, the Orgrimmar guy shouts when it's in Mulgore, and the IF guy when it's at Elwyn.

**Comment by Nerillida** [comment]
Mis clicked close, not sure how to unclose.

**Comment by Nerillida** [comment]
OK, found it,

**Comment by smaitch** [comment]
With the new change in code I made just a bit ago Classic can detect Darkmoon Faire, so with the quest properly marked as Darkmoon Faire, her pins will only appear when the faire is present.

**Comment by Nerillida** [comment]
Yes,sure, but I was trying to avoid them showing in both locations.
Right now, with the NPCs having two locations, either directly or via aliases, and the quests having the same ids in each location, there's no way of avoiding this.
UNLESS, you have a second DMF holiday code and use alias quests MAYBE. Not tried that.

**Comment by smaitch** [comment]
I would like to get rid of the alias quest feature if possible because it causes more headaches than it solves.  But it does not sound like this is an alias quest scenario.  Either the same quest can be gotten by faction specific NPCs which would make use of alias NPCs, or the same quest can be gotten by both factions in both places which would mean the same NPC should have multiple locations on the map simultaneously.

**Comment by Nerillida** [comment]
The NPCs are not factioned. 
Alliance can travel to Mulgore and to quests there.
Horde can do the same in Elwyn.
However, the sites alternate, there will be one in Mulgore very soon, next month it will be in Elwyn.
The map pins do/will not make it clear which one is current.

**Comment by smaitch** [comment]
Oh, I understand.  The faire is in different locations each month.  I had forgotten since Retail went to Darkmoon Island.  So, you are seeing the pin appear in both locations, but the faire is only in one.  So we have to determine which location the faire is in.

**Comment by Nerillida** [comment]
The next DMF is in Mulgore, the carneys are building it now.
Possibly Monday.
if(this date range)
G[14828]={'HF 1429:41.50,68.90'} | -- Gelvas Grimegate
else -- other date range
G[14828]={'HF 1412:xx,yy'} | -- Gelvas Grimegate
end if
or something like that, but that seem klutzy.

**Comment by smaitch** [comment]
OK, I am adding Darkmoon Faire location in Classic as a phase.  The two possible values are 1 for Elwynn Forest and 2 for Mulgore.  This will mean you can use AP:xxxx:=00001;yyyy:=00002 where the xxx NPC is for Elwynn Forest and the yyy NPC is more Mulgore.  I will push these changes today so we should be able to test for Monday when the Darkmoon Faire arrives.

**Comment by Nerillida** [comment]
You may want to wait until I send you the DMF data, I will be finished overnight, UK time, say 8-10 hours.

**Comment by Nerillida** [comment]
Could you edit 

G[14828]={'HF 1429:41.50,68.90'} | -- Gelvas Grimegate

to show the syntax, with dummy location for Mulgore

Please and thanks

**Comment by smaitch** [comment]
It's the quest that gets the AP: and TP: codes instead of normal A: and T: codes.  The NPCs just need one for one zone and an alias one for the other zone to be used in the AP: and TP: codes.

**Comment by smaitch** [comment]
I would make your Kerri example above look like:
G[7889]='HF K0601 L001 N255 AP:14832:=00001;514832:=00002 TP:14832:=00001;514832:=00002 E31727' -- Coarse Weightstone
and the NPC entries:
G[14832]={'HF 1429:40.50,69.90'} -- Kerri Hicks (Elwynn Forest Darkmoon Faire)
G[514832]={'HF 1412:37.80,39.80 A:14832'} -- Kerri Hicks (Mulgore Darkmoon Faire)

**Comment by Nerillida** [comment]
Thanks,

Just have to do the paladin issue. 😀Then you can rest.

**Comment by Nerillida** [comment]
Ready to go - finger crossed

**Comment by Nerillida** [comment]
https://classic.wowhead.com/guides/classic-darkmoon-faire
gives dates
NOTE
the "barkers" appear before the actual faire dates, see the table there. You may need to allow for this somehow.

**Comment by smaitch** [comment]
OK, the latest Grail now has HG as the special opening the Darkmoon Faire "holiday" and the barker quests have been marked for that holiday.
