### ISSUE TITLE
attempt to index field '?' (a nil value) error occurring after update.

### ISSUE THREAD

**Issue by Ookami313** [smaitch/Grail#123]
Updated to retail version 107. Following error occurs when logging into the game. Thanks.

Date: 2020-02-06 17:05:17
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Grail\Grail.lua line 3576:
   attempt to index field '?' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Grail\Grail.lua"]:3576: _LearnWorldQuest()
   [string "@Grail\Grail.lua"]:3447: _AddWorldQuests()
   [string "@Grail\Grail.lua"]:2052: ?()
   [string "@Grail\Grail.lua"]:10472: _Tooltip_OnEvent()
   [string "@Grail\Grail.lua"]:11058:
      Grail\Grail.lua:11058
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:

**Comment by smaitch** [comment]
A fix has been created for the next release of Grail.
