### ISSUE TITLE
Classic - errors

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#124]
(1)
Date: 2020-02-07 12:18:18
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Grail\Grail.lua line 4052:
   attempt to compare nil with number
Debug:
   Grail\Grail.lua:4052: CelebratingHoliday()
   Grail\Grail.lua:7771:
      Grail\Grail.lua:7730
   (tail call): ?
   Grail\Grail.lua:10270: StatusCode()
   Grail\Grail.lua:3980: CanAcceptQuest()
   Grail\Grail.lua:6127: f()
   Grail\Grail.lua:3711: _AllEvaluateTrueS()
   Grail\Grail.lua:3811:
      Grail\Grail.lua:3792
   (tail call): ?
   (tail call): ?
   Grail\Grail.lua:7723: MeetsPrerequisites()
   Grail\Grail.lua:10261: StatusCode()
   Grail\Grail.lua:4233: ClassificationOfQuestCode()
   Wholly\Wholly.lua:1426: _ClassifyQuestsInMap()
   Wholly\Wholly.lua:1877: _ForcePanelMapArea()
   Wholly\Wholly.lua:4406: UpdateQuestCaches()
   Wholly\Wholly.lua:955: ?()
   Wholly\Wholly.lua:2521: _OnEvent()
   Wholly\Wholly.lua:4422:
      Wholly\Wholly.lua:4422
Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Interface\AddOns\Grail\Grail.lua:9085
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Interface\AddOns\Grail\Grail.lua:6972
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Interface\AddOns\Grail\Grail.lua:9683
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Interface\AddOns\Grail\Grail.lua:3323
 QuestLocationsAccept = <function> defined @Interface\AddOns\Grail\Grail.lua:9243
 IsAvailable = <function> defined @Interface\AddOns\Grail\Grail.lua:6954
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Interface\AddOns\Grail\Grail.lua:6659
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Interface\AddOns\Grail\Grail.lua:6687
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:5093
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:8356
 _MarkQuestType = <function> defined @Interface\AddOns\Grail\Grail.lua:5462
 receivedCalendarUpdateEventList = false
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Interface\AddOns\Grail\Grail.lua:9414
 _ProcessServerBackup = <function> defined @Interface\AddOns\Grail\Grail.lua:8774
 bitMaskQuestVariableLevel = 4278190080
 MeetsRequirementGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:7950
 _EvaluateCodeAsPrerequisite = <function> defined @Interface\AddOns\Grail\Grail.lua:5976
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Interface\AddOns\Grail\Grail.lua:8035
 DoesNPCExist = <function> defined @Interface\AddOns\Grail\Grail.lua:5941
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Interface\AddOns\Grail\Grail.lua:3688
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Interface\AddOns\Grail\Grail.lua:8221
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Interface\AddOns\Grail\Grail.lua:3151
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Interface\AddOns\Grail\Grail.lua:7517
 _HandleEventAchievementEarned = <function> defined @Interface\AddOns\Grail\Grail.lua:6654
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 16384
 _ReputationExceeds = <function> defined @Interface\AddOns\Grail\Grail.lua:9871
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = false
 LearnObjectName = <function> defined @Interface\AddOns\Grail\Grail.lua:7443
 _ContainsAliasNPC = <function> defined @Interface\AddOns\Grail\Grail.lua:5683
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Interface\AddOns\Grail\Grail.lua:9970
 QuestBreadcrumbs = <function> defined @Interface\AddOns\Grail\Grail.lua:9079
 NPCName = <function> defined @Interface\AddOns\Grail\Grail.lua:8173
 experimental = false
 cachedBagItems = <table> {
 }
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Interface\AddOns\Grail\Grail.lua:10517
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 _FactionsFromQuestGivers = <function> defined @Interface\AddOns\Grail\Grail.lua:7852
 QuestOnAcceptCompletes = <function> defined @Interface\AddOns\Grail\Grail.lua:9426
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 celebratingHolidayCache = <table> {
 }
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:7006
 bitMaskCanGetUnused8 = 4194304
 bitMaskCanGetUnused15 = 1073741824
 MeetsRequirementGroupPossibleToComplete = <function> defined @Interface\AddOns\Grail\Grail.lua:7978
 questReputations
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  auccheapsearcher, v20190917r3
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BadBoy, vv1-classic
  BadBoyCCleaner, vv8.2.0
  BadBoyGuilded, vv8.2.0
  BasicChatMods, vv4-classic
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.10.00
  ClassicCastbars, vv1.2.1
  ClassicCastbarsOptions, v
  ClassicSpellActivations, v
  ClassTrainerPlus, v0.5-beta
  CTBarMod, v8.3.0.3
  CTBuffMod, v8.3.0.3
  CTCore, v8.3.0.1
  CTLibrary, v8.3.0.3
  CTMailMod, v8.3.0.1
  CTMapMod, v8.3.0.3
  CTPartyBuffs, v8.2.5.6
  CTUnitFrames, v8.3.0.2
  DidIDoIt, v1.2.0
  EMAClassic, vv1.13.2-Release-v0.6(121022)
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtVendorUIClassic, v1.0.4
  FloAspectBar, v
  FloTotemBar, v
  GatherMate2, v1.45.4
  GlobalIgnoreList, v1.13.2
  Grail, v107
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v27178
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v29297
  GrailReputationsclassic, v007
  GrailWhen, v002
  GSE, v2.4.25
  GSEGUI, v2.4.25
  GSELDB, v2.4.25
  Informant, v8.2.6508 (SwimmingSeadragon)
  ISBoxer, v1.0
  LetMeCast, v1.3
  MageButtons, v1.0
  Mapster, v1.8.5
  Misspelled, v1.7.7
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  OmniCC, v8.2.4
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v5.5.1
  QuestLogEx, v1.2
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  SpamThrottleClassic, vv4.0c
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TFTB, v1.10
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  WhatsTraining, v1.8.7
  Wholly, v077
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=961)

(2)
 			elseif 'C' == holidayCode and self.existsClassic then
 				-- Midsummer Fire Festival 6/21 10h00 -> 7/5 10h00

Should be 'M'

thanks

**Comment by smaitch** [comment]
Number 2 is handled for next Grail release.  Still cannot determine what is happening for #1.
