### ISSUE TITLE
Grail, Grail-Achievements error messages

### ISSUE THREAD

**Issue by StanoRiga** [smaitch/Grail#125]
I have the following 3 error messages every time I load the interface

### 1st
13x Grail\Grail-107.lua:8613: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Grail\Grail-107.lua"]:8613: in function `?'
[string "@Grail\Grail-107.lua"]:1341: in function `?'
[string "@Grail\Grail-107.lua"]:10472: in function `_Tooltip_OnEvent'
[string "@Grail\Grail-107.lua"]:11058: in function <Grail\Grail.lua:11058>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

### 2nd
13x ...aceGrail-Achievements\Grail-Achievements-011.lua:7183: attempt to index field '?' (a nil value)
[string "@Grail-Achievements\Grail-Achievements-011.lua"]:7183: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Grail\Grail-107.lua"]:7464: in function `LoadAddOn'
[string "@Wholly\Wholly-077.lua"]:551: in function `configurationScript9'
[string "@Wholly\Wholly-077.lua"]:658: in function `?'
[string "@Wholly\Wholly-077.lua"]:2521: in function `_OnEvent'
[string "@Wholly\Wholly-077.lua"]:4422: in function <Wholly\Wholly.lua:4422>

Locals:
pairs = <function> defined =[C]:-1
tContains = <function> defined @SharedXML\Util.lua:166
tinsert = <function> defined =[C]:-1
tonumber = <function> defined =[C]:-1
wipe = <function> defined =[C]:-1
GetAchievementInfo = <function> defined =[C]:-1
GetBuildInfo = <function> defined =[C]:-1
Grail_Achievements_File_Version = 10
originalMem = 333849
debugStartTime = 469275.703700
supportedFactions = <table> {
 1 = "Alliance"
 2 = "Horde"
}
mapKalimdor = 12
mapEasternKingdoms = 13
mapOutland = 101
mapNorthrend = 113
mapTheMaelstrom = 948
mapPandaria = 424
mapDraenor = 572
mapBrokenIsles = 619
mapArgus = 905
mapZandalar = 875
mapKulTiras = 876
G = <table> {
 2 = <table> {
 }
 32968 = <table> {
 }
 8308 = <table> {
 }
 24933 = <table> {
 }
 25061 = <table> {
 }
 25317 = <table> {
 }
 34504 = <table> {
 }
 25701 = <table> {
 }
 25957 = <table> {
 }
 26213 = <table> {
 }
 26341 = <table> {
 }
 9140 = <table> {
 }
 26597 = <table> {
 }
 26725 = <table> {
 }
 9396 = <table> {
 }
 27237 = <table> {
 }
 27493 = <table> {
 }
 9716 = <table> {
 }
 9780 = <table> {
 }
 27877 = <table> {
 }
 9972 = <table> {
 }
 10036 = <table> {
 }
 28389 = <table> {
 }
 28645 = <table> {
 }
 32969 = <table> {
 }
 10484 = <table> {
 }
 10612 = <table> {
 }
 34505 = <table> {
 }
 10804 = <table> {
 }
 10868 = <table> {
 }
 10996 = <table> {
 }
 11188 = <table> {
 }
 11252 = <table> {
 }
 11316 = <table> {
 }
 11380 = <table> {
 }
 11508 = <table> {
 }
 11572 = <table> {
 }
 11636 = <table> {
 }
 11700 = <table> {
 }
 11764 = <table> {
 }
 11828 = <table> {
 }
 11892 = <table> {
 }
 11956 = <table> {
 }
 12020 = <table> {
 }
 12084 = <table> {
 }
 12148 = <table> {
 }
 12212 = <table> {
 }
 12276 = <table> {
 }
 12340 = <table> {
 }
 12404 = <table> {
 }
 12468 = <table> {
 }
 12532 = <table> {
 }
 12596 = <table> {
 }
 12660 = <table> {
 }
 25574 = <table> {
 }
 12852 = <table> {
 }
 12916 = <table> {
 }
 12980 = <table> {
 }
 13044 = <table> {
 }
 26214 = <table> {
 }
 13172 = <table> {
 }
 13236 = <table> {
 }
 26598 = <table> {
 }
 13364 = <table> {
 }
 13492 = <table> {
 }
 13556 = <table> {
 }
 13620 = <table> {
 }
 27366 = <table> {
 }
 27622 = <table> {
 }
 13876 = <table> {
 }
 13940 = <table> {
 }
 14004 = <table> {
 }
 14068 = <table> {
 }
 14132 = <table> {
 }
 14196 = <table> {
 }
 14260 = <table> {
 }
 14324 = <table> {
 }
 14388 = <table> {
 }
 29030 = <table> {
 }
 29670 = <table> {
 }
 51401 = <table> {
 }
 24551 = <table> {
 }
 8309 = <table> {
 }
 25063 = <table> {
 }
 25191 = <table> {
 }
 25319 = <table> {
 }
 25447 = <table> {
 }
 25575 = <table> {
 }
 25703 = <table> {
 }
 25959 = <table> {
 }
 26087 = <table> {
 }
 26215 = <table> {
 }
 26343 = <table> {
 }
 26599 = <table> {
 }
 26727 = <table> {
 }
 9397 = <table> {
 }
 27239 = <table> {
 }
 27367 = <table> {
 }
 27623 = <table> {
 }
 9781 = <table> {
 }
 9845 = <table> {
 }
 9973 = <table> {
 }
 10037 = <table> {
 }
 10101 = <table> {
 }
 1271 = <table> {
 }
 10229 = <table> {
 }
 10293 = <table> {
 }
 29031 = <table> {
 }
 10485 = <table> {
 }
 10613 = <table> {
 }
 10677 = <table> {
 }
 10805 = <table> {
 }
 10869 = <table> {
 }
 10997 = <table> {
 }
 11061 = <table> {
 }
 11253 = <table> {
 }
 11317 = <table> {
 }
 11381 = <table> {
 }
 11509 = <table> {
 }
 11573 = <table> {
 }
 11637 = <table> {
 }
 11701 = <table> {
 }
 11765 = <table> {
 }
 11829 = <table> {
 }
 11893 = <table> {
 }
 11957 = <table> {
 }
 12085 = <table> {
 }
 12149 = <table> {
 }
 12213 = <table> {
 }
 12277 = <table> {
 }
 12341 = <table> {
 }
 12469 = <table> {
 }
 12533 = <table> {
 }
 12597 = <table> {
 }
 12661 = <table> {
 }
 25448 = <table> {
 }
 25576 = <table> {
 }
 12853 = <table> {
 }
 25832 = <table> {
 }
 25960 = <table> {
 }
 13045 = <table> {
 }
 26344 = <table> {
 }
 13237 = <table> {
 }
 26600 = <table> {
 }
 26728 = <table> {
 }
 13493 = <table> {
 }
 13557 = <table> {
 }
 13621 = <table> {
 }
 27368 = <table> {
 }
 27496 = <table> {
 }
 27624 = <table> {
 }
 13877 = <table> {
 }
 27880 = <table> {
 }
 28136 = <table> {
 }
 28264 = <table> {
 }
 14197 = <table> {
 }
 14261 = <

### 3rd
119x (null)

**Comment by smaitch** [comment]
For the first one are you getting an error message in the console about not being able to load the NPCs file?

**Comment by smaitch** [comment]
In any case Grail has been updated for the next release to better handle situations for #1 and #2 so those errors should no longer happen.

**Comment by StanoRiga** [comment]
Hi. I receive only these 3 errors (via bugsack) on ervery UI load (just load, not doing anything).
I have to admint that I added #3 because before updating Grail I had 0 errors, so I just assume that #3 also belongs to Grail. I will wait for the next release and give feedback then. Thank you for your work!

**Comment by StanoRiga** [comment]
confirm that #1 and #2 and #3 is fixed in todays release. Will close this issue and open a new one for the error that is now shown ;)
