### ISSUE TITLE
Retail error

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#127]
Friend boosted a new character to 110 (old boost).

Felstorm's Plea 41035
Has 43635 as a prerequisite and this gives Dalaran hearthstone as a reward.
Boosted characters start with the hearthstone. The quest is unavailable to them.

Wowhead has a note
[THIS IS A TEMPORARY QUEST TO GET YOU TO DALARAN IN THE BROKEN ISLES.]

**Comment by smaitch** [comment]
Grail has been updated to need either the quest or the Dalaran Hearthstone as the prerequisite.
