### ISSUE TITLE
Grail error message

### ISSUE THREAD

**Issue by Numira123** [smaitch/Grail#128]
Message: Interface\AddOns\Grail\Grail.lua:3576: attempt to index field '?' (a nil value)
Time: Sun Feb  9 23:45:04 2020
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:3576: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\Grail\Grail.lua"]:3576: in function `_LearnWorldQuest'
[string "@Interface\AddOns\Grail\Grail.lua"]:3447: in function `_AddWorldQuests'
[string "@Interface\AddOns\Grail\Grail.lua"]:2052: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:10472: in function `_Tooltip_OnEvent'
[string "@Interface\AddOns\Grail\Grail.lua"]:11058: in function <Interface\AddOns\Grail\Grail.lua:11058>

Locals: self = <table> {
 QuestBreadcrumbsFor = <function> defined @Interface\AddOns\Grail\Grail.lua:9088
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Interface\AddOns\Grail\Grail.lua:6974
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Interface\AddOns\Grail\Grail.lua:9686
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Interface\AddOns\Grail\Grail.lua:3324
 QuestLocationsAccept = <function> defined @Interface\AddOns\Grail\Grail.lua:9246
 IsAvailable = <function> defined @Interface\AddOns\Grail\Grail.lua:6956
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Interface\AddOns\Grail\Grail.lua:6661
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Interface\AddOns\Grail\Grail.lua:6689
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:5095
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:8359
 _MarkQuestType = <function> defined @Interface\AddOns\Grail\Grail.lua:5464
 receivedCalendarUpdateEventList = true
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Interface\AddOns\Grail\Grail.lua:9417
 _ProcessServerBackup = <function> defined @Interface\AddOns\Grail\Grail.lua:8777
 bitMaskQuestVariableLevel = 4278190080
 MeetsRequirementGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:7952
 _EvaluateCodeAsPrerequisite = <function> defined @Interface\AddOns\Grail\Grail.lua:5978
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Interface\AddOns\Grail\Grail.lua:8037
 DoesNPCExist = <function> defined @Interface\AddOns\Grail\Grail.lua:5943
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Interface\AddOns\Grail\Grail.lua:3690
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Interface\AddOns\Grail\Grail.lua:8223
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Interface\AddOns\Grail\Grail.lua:3152
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Interface\AddOns\Grail\Grail.lua:7519
 _HandleEventAchievementEarned = <function> defined @Interface\AddOns\Grail\Grail.lua:6656
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 16384
 _ReputationExceeds = <function> defined @Interface\AddOns\Grail\Grail.lua:9874
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = true
 LearnObjectName = <function> defined @Interface\AddOns\Grail\Grail.lua:7445
 _ContainsAliasNPC = <function> defined @Interface\AddOns\Grail\Grail.lua:5685
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Interface\AddOns\Grail\Grail.lua:9973
 QuestBreadcrumbs = <function> defined @Interface\AddOns\Grail\Grail.lua:9082
 NPCName = <function> defined @Interface\AddOns\Grail\Grail.lua:8175
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Interfa

**Comment by smaitch** [comment]
Grail has been updated to work around this problem in the next release.
