### ISSUE TITLE
Classic - error

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#129]
Using latest versions

On entering Elwyn Forest OR displaying its map.

With only Wholly/Grail loaded

Message: Interface\AddOns\Grail\Grail.lua:9882: attempt to index global 'C_Reputation' (a nil value)
Time: Tue Feb 11 19:18:13 2020
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:9882: attempt to index global 'C_Reputation' (a nil value)
Interface\AddOns\Grail\Grail.lua:9882: in function `_ReputationExceeds'
Interface\AddOns\Grail\Grail.lua:6148: in function `f'
Interface\AddOns\Grail\Grail.lua:3711: in function `_AllEvaluateTrueS'
Interface\AddOns\Grail\Grail.lua:3811: in function <Interface\AddOns\Grail\Grail.lua:3792>
(tail call): ?
(tail call): ?
Interface\AddOns\Grail\Grail.lua:7723: in function `MeetsPrerequisites'
Interface\AddOns\Grail\Grail.lua:10261: in function `StatusCode'
Interface\AddOns\Grail\Grail.lua:4233: in function `ClassificationOfQuestCode'
Interface\AddOns\Wholly\Wholly.lua:1426: in function `_ClassifyQuestsInMap'
Interface\AddOns\Wholly\Wholly.lua:790: in function `RefreshAllData'
...ns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:76: in function `OnMapChanged'
...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:529: in function `OnMapChanged'
...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:115: in function `OnMapChanged'
...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:37: in function `SetMapID'
...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:731: in function `NavigateToCursor'
...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:113: in function <...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:105>

Locals: self = <table> {
 QuestBreadcrumbsFor = <function> defined @Interface\AddOns\Grail\Grail.lua:9085
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Interface\AddOns\Grail\Grail.lua:6972
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Interface\AddOns\Grail\Grail.lua:9683
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Interface\AddOns\Grail\Grail.lua:3323
 QuestLocationsAccept = <function> defined @Interface\AddOns\Grail\Grail.lua:9243
 IsAvailable = <function> defined @Interface\AddOns\Grail\Grail.lua:6954
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Interface\AddOns\Grail\Grail.lua:6659
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Interface\AddOns\Grail\Grail.lua:6687
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:5093
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:8356
 _MarkQuestType = <function> defined @Interface\AddOns\Grail\Grail.lua:5462
 receivedCalendarUpdateEventList = false
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Interface\AddOns\Grail\Grail.lua:9414
 _ProcessServerBackup = <function> defined @Interface\AddOns\Grail\Grail.lua:8774
 bitMaskQuestVariableLevel = 4278190080
 MeetsRequirementGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:7950
 _EvaluateCodeAsPrerequisite = <function> defined @Interface\AddOns\Grail\Grail.lua:5976
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Interface\AddOns\Grail\Grail.lua:8035
 DoesNPCExist = <function> defined @Interface\AddOns\Grail\Grail.lua:5941
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Interface\AddOns\Grail\Grail.lua:3688
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Interface\AddOns\Grail\Grail.lua:8221
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Interface\AddOns\Grail\Grail.lua:3151
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Interface\AddOns\Grail\Grail.lua:7517
 _HandleEventAchievementEarned = <function> defined @Interface\AddOns\Grail\Grail.lua:6654
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMappin

**Comment by smaitch** [comment]
Thank goodness this is not happening in the released code as we do not have any reputation requirements yet.  When the pull request is merged it will happen.  I have a fix to avoid this happen in the next Grail.

**Comment by Nerillida** [comment]
Thanks
