### ISSUE TITLE
Grail.lua script ran too long

### ISSUE THREAD

**Issue by SqtYork** [smaitch/Grail#13]
Date: 2017-06-29 00:30:24
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Grail\Grail.lua line 6296:
   script ran too long
Debug:
   Grail\Grail.lua:6296: LoadAddOn()
   Wholly\Wholly.lua:492: configurationScript9()
   Wholly\Wholly.lua:578: ?()
   Wholly\Wholly.lua:2332: _OnEvent()
   Wholly\Wholly.lua:2514:
      Wholly\Wholly.lua:2514
Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Interface\AddOns\Grail\Grail.lua:7721
 bitMaskClassPriest = 256
 continentIndexMapping = <table> {
 }
 IsBugged = <function> defined @Interface\AddOns\Grail\Grail.lua:5821
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Interface\AddOns\Grail\Grail.lua:8257
 bitMaskCompleted = 1
 tooltip = com_mithrandir_grailTooltip {
 }
 QuestLocationsAccept = <function> defined @Interface\AddOns\Grail\Grail.lua:7857
 IsAvailable = <function> defined @Interface\AddOns\Grail\Grail.lua:5803
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Interface\AddOns\Grail\Grail.lua:5508
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Interface\AddOns\Grail\Grail.lua:5536
 bitMaskQuestLegendary = 4096
 continentEasternKingdoms = 2
 _RemoveDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:4027
 reputationFriends = <table> {
 }
 questsLoremaster = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:7116
 _MarkQuestType = <function> defined @Interface\AddOns\Grail\Grail.lua:4383
 receivedCalendarUpdateEventList = true
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Interface\AddOns\Grail\Grail.lua:8011
 _ProcessServerBackup = <function> defined @Interface\AddOns\Grail\Grail.lua:7428
 bodyGuardLevel = <table> {
 }
 MeetsRequirementGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:6709
 _EvaluateCodeAsPrerequisite = <function> defined @Interface\AddOns\Grail\Grail.lua:4876
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Interface\AddOns\Grail\Grail.lua:6794
 DoesNPCExist = <function> defined @Interface\AddOns\Grail\Grail.lua:4841
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Interface\AddOns\Grail\Grail.lua:3003
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Interface\AddOns\Grail\Grail.lua:6980
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Interface\AddOns\Grail\Grail.lua:6332
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 16384
 _ReputationExceeds = <function> defined @Interface\AddOns\Grail\Grail.lua:8443
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 LearnObjectName = <function> defined @Interface\AddOns\Grail\Grail.lua:6277
 _ContainsAliasNPC = <function> defined @Interface\AddOns\Grail\Grail.lua:4595
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Interface\AddOns\Grail\Grail.lua:8533
 QuestBreadcrumbs = <function> defined @Interface\AddOns\Grail\Grail.lua:7715
 NPCName = <function> defined @Interface\AddOns\Grail\Grail.lua:6927
 experimental = false
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Interface\AddOns\Grail\Grail.lua:8997
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 QuestOnAcceptCompletes = <function> defined @Interface\AddOns\Grail\Grail.lua:8023
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 1073741824
 _IntegerFromStringPosition = <function> defined @Interface\AddOns\Grail\Grail.lua:4438
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:5855
 MeetsRequirementGroupPossibleToComplete = <function> defined @Interface\AddOns\Grail\Grail.lua:6737
 questReputations = <table> {
 }
 versionNumber = 89
 _ProcessQuestsForHandlers = <function> defined @Interface\AddOns\Grail\Grail.lua:7373
 _EvaluateCodeAsNotInLogImpossible = <function> defined @Interface\AddOns\Grail\Grail.lua:4857
 invalidateGroupWithering = 1
 _QuestAbandonStop = <function> defined @Interface\AddOns\Grail\Grail.lua:7684
 bitM
AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  WowheadLooter, v70204
  AckisRecipeList, v7.2.0.2
  AckisRecipeListQuickScan, v7.2.0.1
  Atlas, vv1.41.18
  AtlasArena, v1.06.05
  AtlasBattlegrounds, v1.39.00
  AtlasBurningCrusade, v1.39.00
  AtlasCataclysm, vv1.41.02
  AtlasClassicWoW, v1.39.00
  AtlasClassOrderHalls, vv1.41.06
  AtlasDungeonLocs, v1.39.00
  AtlasLegion, vv1.41.05
  AtlasMistsofPandaria, vv1.41.00
  AtlasOutdoorRaids, vv1.41.05
  AtlasScenarios, vv1.41.00
  AtlasTransportation, v1.40.00
  AtlasWarlordsofDraenor, v1.39.00
  AtlasWorldEvents, vv3.21
  AtlasWrathoftheLichKing, vv1.41.00
  AtlasLoot, vv8.04.04
  AtlasLootBurningCrusade, vv8.04.04
  AtlasLootCataclysm, vv8.04.04
  AtlasLootClassic, vv8.04.04
  AtlasLootLegion, vv8.04.04
  AtlasLootMistsofPandaria, vv8.04.04
  AtlasLootWarlordsofDraenor, vv8.04.04
  AtlasLootWrathoftheLichKing, vv8.04.04
  AtlasMajorCitiesEnhanced, vv1.14
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  AutoRepair, v
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  CollectMe, v2.9.3
  Configator, v5.1.DEV.406(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  DugisGuideViewerZ, v4.210
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  Grail, v089
  GrailAchievements, v011
  GrailQuestsenUS, v22996
  GrailReputations, v007
  GrailWhen, v001
  Informant, v7.4.5714 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  Wholly, v063
  BlizRuntimeLib_enUS v7.2.5.70200 <none>
  (ck=b72)

**Comment by smaitch** [comment]
Is this problem still happening for you?  I know there was an issue that Blizzard was fixing with the system, and I have not seen this.

**Comment by smaitch** [comment]
One assume this is no longer a problem.
