### ISSUE TITLE
Classic - Grail/Wholly error

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#131]
Mousing over

G[593]='SP K0460 L001 N255 A:2530 T:2530 P:B592+K10003912 E31727'

gives the error 

Date: 2020-02-12 16:33:32
ID: 1
Error occured in: Global
Count: 6
Message: ..\AddOns\Wholly\Wholly.lua line 2653:
   bad argument #3 to 'format' (string expected, got nil)
Debug:
   [C]: ?
   Wholly\Wholly.lua:2653: _PrettyQuestString()
   Wholly\Wholly.lua:3204: func()
   Grail\Grail.lua:8495:
      Grail\Grail.lua:8456
   (tail call): ?
   Wholly\Wholly.lua:3170: _QuestInfoSection()
   Wholly\Wholly.lua:3008: _PopulateTooltipForQuest()
   Wholly\Wholly.lua:1306: ButtonEnter()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1
Locals:
(*temporary) = "|c%s%s [%s]"
(*temporary) = "FFFF0000"
(*temporary) = nil
(*temporary) = "Item"
(*temporary) = "string expected, got nil"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  auccheapsearcher, v20190917r3
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BadBoy, vv1-classic
  BadBoyCCleaner, vv8.2.0
  BadBoyGuilded, vv8.2.0
  BasicChatMods, vv4-classic
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.10.00
  ClassicAutoDismount, v1.01
  ClassicCastbars, vv1.2.1
  ClassicCastbarsOptions, v
  ClassicSpellActivations, v
  ClassTrainerPlus, v0.5-beta
  CTBarMod, v8.3.0.3
  CTBuffMod, v8.3.0.3
  CTCore, v8.3.0.1
  CTLibrary, v8.3.0.3
  CTMailMod, v8.3.0.1
  CTMapMod, v8.3.0.3
  CTPartyBuffs, v8.2.5.6
  CTUnitFrames, v8.3.0.2
  DidIDoIt, v1.2.0
  EMAClassic, vv1.13.2-Release-v0.6(121022)
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtVendorUIClassic, v1.0.4
  FloAspectBar, v
  FloTotemBar, v
  GatherMate2, v1.45.4
  GlobalIgnoreList, v1.13.2
  Grail, v107
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v27178
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v29297
  GrailReputationsclassic, v007
  GSE, v2.4.25
  GSEGUI, v2.4.25
  GSELDB, v2.4.25
  Informant, v8.2.6508 (SwimmingSeadragon)
  ISBoxer, v1.0
  LetMeCast, v1.3
  MageButtons, v1.0
  Mapster, v1.8.5
  Misspelled, v1.7.7
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  OmniCC, v8.2.4
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v5.5.1
  QuestLogEx, v1.2
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  SpamThrottleClassic, vv4.0c
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TFTB, v1.10
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  WhatsTraining, v1.8.7
  Wholly, v077
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=96c)

I am editing it to a repeatable.

G[593]='SP K0461 L001 N255 A:2530 T:2530 P:B592+K10003912 E31727'

**Comment by smaitch** [comment]
The next Grail has this corrected.  There was a missing 0 from the K part of the P: code.
