### ISSUE TITLE
Classic 108 prerelease

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#133]
(1) maybe you could make the "UNKNOWNS" something more meaningful.

![Screen Shot 2020-02-14 at 03 30 39](https://user-images.githubusercontent.com/55858788/74499766-b2566700-4edc-11ea-8b1a-f7a65aeb11a5.png)

(2) on loading a character and entering Elwyn Forest/Mulgore  or opening its list in Wholly and mousing over a DMF quest(s)

*** Grail.ReputationNameAndLevelName problem: FACTION_STANDING_LABEL%d_FEMALE 38D 3000 false false
multiple of above
*** Grail.ReputationNameAndLevelName problem: FACTION_STANDING_LABEL%d_FEMALE 38D 2250 false false
several and also other rep values

The display seems inconsistent, the same quests are disabled in both areas and others are allowed in both areas.

![Screen Shot 2020-02-14 at 03 43 10](https://user-images.githubusercontent.com/55858788/74499736-96eb5c00-4edc-11ea-92bf-3e70f7b19962.png)

These errors occur with a character who has DMF rep and with one who has none in rep pane.

NOTE: The barkers for the DMF appear during AND 2(?3) days before. Possible need different phases.

ALSO - my latest pull request has some corrections from previous pull, including correctly formed aliases for DMF, makes no difference if they are fixed regarding above.

**Comment by smaitch** [comment]
I have updated Grail with the following:
(1) Phase 0 is now called Darkmoon Faire, which means the UNKNOWN is now addressed.
(2) The odd Darkmoon Faire reputation restrictions are now implemented using the values from the wowhead Classic Darkmoon Faire page.  I hope these values are correct.
(3) The Classic Darkmoon Faire quests marked with reputation limitations are now using the values in #2, which means the ReputationNameAndLevelName issue should go away.
We should come up with another holiday (perhaps "G") which can be used for the days the barker quests are available before the actual Darkmoon Faire is present.

**Comment by Nerillida** [comment]
Thank you, I appreciate your effort.

**Comment by Nerillida** [comment]
Regarding (2), I had read many individual posts to get my values, only later coming across the Wowhead page. My money would be on the Wowhead data.

**Comment by smaitch** [comment]
#3 has been dealt with by adding a new "holiday" marked as HG for the barkers.
