### ISSUE TITLE
Script ran too long retail

### ISSUE THREAD

**Issue by Naab25** [smaitch/Grail#140]
Date: 2020-02-23 22:58:48
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Grail\Grail.lua line 9748:
   script ran too long
Debug:
   [string "@Grail\Grail.lua"]:9748: _RawNPCLocations()
   [string "@Grail\Grail.lua"]:8242: NPCLocations()
   [string "@Grail\Grail.lua"]:9374:
      Grail\Grail.lua:9362
   [string "=(tail call)"]: ?
   [string "@Grail\Grail.lua"]:5883: ?()
   [string "@Grail\Grail.lua"]:1386: ?()
   [string "@Grail\Grail.lua"]:10580: _Tooltip_OnEvent()
   [string "@Grail\Grail.lua"]:11166:
      Grail\Grail.lua:11166
Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Interface\AddOns\Grail\Grail.lua:9196
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Interface\AddOns\Grail\Grail.lua:7067
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Interface\AddOns\Grail\Grail.lua:9794
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Interface\AddOns\Grail\Grail.lua:3390
 QuestLocationsAccept = <function> defined @Interface\AddOns\Grail\Grail.lua:9354
 IsAvailable = <function> defined @Interface\AddOns\Grail\Grail.lua:7049
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Interface\AddOns\Grail\Grail.lua:6754
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Interface\AddOns\Grail\Grail.lua:6782
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:5187
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:8463
 _MarkQuestType = <function> defined @Interface\AddOns\Grail\Grail.lua:5556
 receivedCalendarUpdateEventList = false
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Interface\AddOns\Grail\Grail.lua:9525
 _ProcessServerBackup = <function> defined @Interface\AddOns\Grail\Grail.lua:8885
 bitMaskQuestVariableLevel = 4278190080
 MeetsRequirementGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:8045
 _EvaluateCodeAsPrerequisite = <function> defined @Interface\AddOns\Grail\Grail.lua:6071
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Interface\AddOns\Grail\Grail.lua:8130
 DoesNPCExist = <function> defined @Interface\AddOns\Grail\Grail.lua:6036
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Interface\AddOns\Grail\Grail.lua:3756
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Interface\AddOns\Grail\Grail.lua:8316
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Interface\AddOns\Grail\Grail.lua:3218
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Interface\AddOns\Grail\Grail.lua:7612
 _HandleEventAchievementEarned = <function> defined @Interface\AddOns\Grail\Grail.lua:6749
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 8192
 _ReputationExceeds = <function> defined @Interface\AddOns\Grail\Grail.lua:9982
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = true
 LearnObjectName = <function> defined @Interface\AddOns\Grail\Grail.lua:7538
 _ContainsAliasNPC = <function> defined @Interface\AddOns\Grail\Grail.lua:5777
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Interface\AddOns\Grail\Grail.lua:10081
 QuestBreadcrumbs = <function> defined @Interface\AddOns\Grail\Grail.lua:9190
 NPCName = <function> defined @Interface\AddOns\Grail\Grail.lua:8268
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Interface\AddOns\Grail\Grail.lua:10628
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 _FactionsFromQuestGivers = <function> defined @Interface\AddOns\Grail\Grail.lua:7947
 QuestOnAcceptCompletes = <function> defined @Interface\AddOns\Grail\Grail.lua:9537
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 celebratingHolidayCache = <table> {
 }
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:7101
 bitMaskCanGetUnused8 = 4194304
 bitMaskCanGetUnused15 = 1073741824
 MeetsRequirementGroupPossibleToComplete = <function> defined @Interface\AddOns\Grail\Grail.lua:8073
 questReputations = <table> {
 }
 _AddThreatQuest
AddOns:
  KalielsTracker, v3.2.1
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AceGUI30SelectablePanel, vv1.0-alpha2
  ActionBarProfiles, v8.2.0
  AdvancedInterfaceOptions, v1.3.4
  Altoholic, v8.3-002
  AtlasLoot, vv8.11.00
  AtlasLootWarlordsofDraenor, vv8.11.00
  Aurora, v8.3.0.3
  AutoLootPlus, v2.0.0-80200
  AutoTurnIn, v7.0.9
  BagBrother, v
  Bagnon, v8.3.4
  BagnonBoE, v1.0
  BagnonItemLevel, v1.0
  Bartender4, v4.9.0
  BonusRollPreview, v80100.47-Release
  ClassOrderHallsComplete, v1.35
  CQuestCounter, v1.4
  DataStore, vr67
  DataStoreAchievements, vr49
  DataStoreAgenda, vr31
  DataStoreAuctions, vr52
  DataStoreCharacters, vr45
  DataStoreContainers, vr61
  DataStoreCrafts, vr84
  DataStoreCurrencies, vr40
  DataStoreGarrisons, vr26
  DataStoreInventory, vr55
  DataStoreMails, vr54
  DataStorePets, vr46
  DataStoreQuests, vr48
  DataStoreReputations, vr45
  DataStoreSpells, vr34
  DataStoreStats, vr33
  DataStoreTalents, vr63
  DBMCore, v8.3.14
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v830r304
  ErrorFilter, vv3.7
  ExaltedPlus, v15
  Grail, v108
  GrailNPCsretail, v27178
  GrailNPCsretailenUS, v27178
  GrailQuestsretail, v31478
  GrailQuestsretailenUS, v31478
  GSE, v2.5.3
  GSEGUI, v2.5.3
  GSELDB, v2.5.3
  GTFO, v4.54
  HandyNotes, vv1.5.9
  HandyNotesArgus, v0.20.0
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.33
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionTreasures, v1
  HandyNotesLostAndFound, v1
  HealBotData, v8.3.0.4
  HealBoten, v8.3.0.4
  HealBotOptions, v8.3.0.4
  Immersion, v1.2.2
  InstancePortals, v25
  LegionInvasionTimer, vv8.3.0
  MacroToolkit, vv7.3.0.2
  MBB, v4.0.1
  MogIt, v3.9.0
  MogItArtifact, v3.9.0
  MogItOneHanded, v3.9.0
  MogItOther, v3.9.0
  MogItPlate, v3.9.0
  MogItRanged, v3.9.0
  MogItTwoHanded, v3.9.0
  mOnArsWardrobeHelper, v1.18.6
  MoveAnything, v17.1.0
  Narcissus, v1.0.7
  NPCScan, v8.0.1.13
  Omen, v3.2.2
  Pathfinder, v1.7.2.1
  Postal, vv3.6.2
  Prat30, v3.7.50
  Prat30Libraries, v
  Quartz, v3.5.2
  ShadowedUnitFrames, vv4.2.9
  Simulationcraft, v1.12.5
  Skada, v1.7.7
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Spy, v3.6.27
  TheUndermineJournal, v5.4.20200204
  TidyPlatesThreatPlates, v9.1.17
  TomCats, v1.4.12
  TomTom, vv80300-1.1.1
  WeakAuras, v2.16.6
  Wholly, v077
  WorldQuestsList, v92
  XLoot, v8.2-1
  XLootFrame, v8.2-1
  XLootGroup, v8.2-1
  XLootMaster, v8.2-1
  XLootMonitor, v8.2-1
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=9b6)

Getting this error

**Comment by smaitch** [comment]
Can you try to use the latest Grail from GitHub to see if this issue still appears for you?

**Comment by Naab25** [comment]
Will try and test it tomorrow and see if any issues pop up

**Comment by Naab25** [comment]
Tested it today and this came out 
Date: 2020-02-28 18:03:18
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Grail\Grail.lua line 8298:
   script ran too long
Debug:
   [string "@Grail\Grail.lua"]:8298: NPCName()
   [string "@Grail\Grail.lua"]:9727: _RawNPCLocations()
   [string "@Grail\Grail.lua"]:8250: NPCLocations()
   [string "@Grail\Grail.lua"]:9382:
      Grail\Grail.lua:9370
   [string "=(tail call)"]: ?
   [string "@Grail\Grail.lua"]:5891: ?()
   [string "@Grail\Grail.lua"]:1389: ?()
   [string "@Grail\Grail.lua"]:10588: _Tooltip_OnEvent()
   [string "@Grail\Grail.lua"]:11174:
      Grail\Grail.lua:11174
Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Interface\AddOns\Grail\Grail.lua:9204
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Interface\AddOns\Grail\Grail.lua:7075
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Interface\AddOns\Grail\Grail.lua:9802
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Interface\AddOns\Grail\Grail.lua:3393
 QuestLocationsAccept = <function> defined @Interface\AddOns\Grail\Grail.lua:9362
 IsAvailable = <function> defined @Interface\AddOns\Grail\Grail.lua:7057
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Interface\AddOns\Grail\Grail.lua:6762
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Interface\AddOns\Grail\Grail.lua:6790
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:5195
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:8471
 _MarkQuestType = <function> defined @Interface\AddOns\Grail\Grail.lua:5564
 receivedCalendarUpdateEventList = false
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Interface\AddOns\Grail\Grail.lua:9533
 _ProcessServerBackup = <function> defined @Interface\AddOns\Grail\Grail.lua:8893
 bitMaskQuestVariableLevel = 4278190080
 MeetsRequirementGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:8053
 _EvaluateCodeAsPrerequisite = <function> defined @Interface\AddOns\Grail\Grail.lua:6079
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Interface\AddOns\Grail\Grail.lua:8138
 DoesNPCExist = <function> defined @Interface\AddOns\Grail\Grail.lua:6044
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Interface\AddOns\Grail\Grail.lua:3764
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Interface\AddOns\Grail\Grail.lua:8324
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Interface\AddOns\Grail\Grail.lua:3221
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Interface\AddOns\Grail\Grail.lua:7620
 _HandleEventAchievementEarned = <function> defined @Interface\AddOns\Grail\Grail.lua:6757
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 8192
 _ReputationExceeds = <function> defined @Interface\AddOns\Grail\Grail.lua:9990
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = true
 LearnObjectName = <function> defined @Interface\AddOns\Grail\Grail.lua:7546
 _ContainsAliasNPC = <function> defined @Interface\AddOns\Grail\Grail.lua:5785
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Interface\AddOns\Grail\Grail.lua:10089
 QuestBreadcrumbs = <function> defined @Interface\AddOns\Grail\Grail.lua:9198
 NPCName = <function> defined @Interface\AddOns\Grail\Grail.lua:8276
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Interface\AddOns\Grail\Grail.lua:10636
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 _FactionsFromQuestGivers = <function> defined @Interface\AddOns\Grail\Grail.lua:7955
 QuestOnAcceptCompletes = <function> defined @Interface\AddOns\Grail\Grail.lua:9545
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 celebratingHolidayCache = <table> {
 }
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:7109
 bitMaskCanGetUnused8 = 4194304
 bitMaskCanGetUnused15 = 1073741824
 MeetsRequirementGroupPossibleToComplete = <function> defined @Interface\AddOns\Grail\Grail.lua:8081
 questReputations = <table> {
 }
 _AddThreatQuest
AddOns:
  KalielsTracker, v3.2.1
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AceGUI30SelectablePanel, vv1.0-alpha2
  ActionBarProfiles, v8.2.0
  AdvancedInterfaceOptions, v1.3.4
  Altoholic, v8.3-002
  AtlasLoot, vv8.12.00
  AtlasLootWarlordsofDraenor, vv8.12.00
  Aurora, v8.3.0.3
  AutoLootPlus, v2.0.0-80200
  BagBrother, v
  Bagnon, v8.3.5
  BagnonBoE, v1.0
  BagnonItemLevel, v1.0
  Bartender4, v4.9.0
  BFAInvasionTimer, vv8.3.0
  BonusRollPreview, v80100.47-Release
  ClassOrderHallsComplete, v1.35
  CQuestCounter, v1.4
  DataStore, vr67
  DataStoreAchievements, vr49
  DataStoreAgenda, vr31
  DataStoreAuctions, vr52
  DataStoreCharacters, vr45
  DataStoreContainers, vr61
  DataStoreCrafts, vr84
  DataStoreCurrencies, vr40
  DataStoreGarrisons, vr26
  DataStoreInventory, vr55
  DataStoreMails, vr54
  DataStorePets, vr46
  DataStoreQuests, vr48
  DataStoreReputations, vr45
  DataStoreSpells, vr34
  DataStoreStats, vr33
  DataStoreTalents, vr63
  DBMCore, v8.3.15
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v830r304
  ErrorFilter, vv3.7
  ExaltedPlus, v15
  Grail, v109
  GrailNPCsretail, v27178
  GrailNPCsretailenUS, v27178
  GrailQuestsretail, v31478
  GrailQuestsretailenUS, v31478
  GSE, v2.5.3
  GSEGUI, v2.5.3
  GSELDB, v2.5.3
  GTFO, v4.55
  HandyNotes, vv1.5.9
  HandyNotesArgus, v0.20.0
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.33
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionTreasures, v1
  HandyNotesLostAndFound, v1
  HealBotData, v8.3.0.4
  HealBoten, v8.3.0.4
  HealBotOptions, v8.3.0.4
  Immersion, v1.2.2
  InstancePortals, v25
  MacroToolkit, vv7.3.0.2
  MBB, v4.0.1
  MogIt, v3.9.0
  MogItArtifact, v3.9.0
  MogItOneHanded, v3.9.0
  MogItOther, v3.9.0
  MogItPlate, v3.9.0
  MogItRanged, v3.9.0
  MogItTwoHanded, v3.9.0
  mOnArsWardrobeHelper, v1.18.6
  MoveAnything, v17.1.0
  Narcissus, v1.0.7
  Omen, v3.2.2
  Pathfinder, v1.7.2.1
  Postal, vv3.6.2
  Prat30, v3.7.50
  Prat30Libraries, v
  Quartz, v3.5.2
  ShadowedUnitFrames, vv4.2.9
  SilverDragon, vv4.0.17
  SilverDragonBattleForAzeroth, vv4.0.17
  SilverDragonBurningCrusade, vv4.0.17
  SilverDragonCataclysm, vv4.0.17
  SilverDragonLegion, vv4.0.17
  SilverDragonMists, vv4.0.17
  SilverDragonVanilla, vv4.0.17
  SilverDragonWarlords, vv4.0.17
  SilverDragonWrath, vv4.0.17
  Simulationcraft, v1.12.5
  Skada, v1.7.7
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Spy, v3.6.27
  TheUndermineJournal, v5.5.20200225
  TidyPlatesThreatPlates, v9.1.18
  TomCats, v1.4.12
  TomTom, vv80300-1.1.1
  WeakAuras, v2.16.6
  Wholly, v077
  WorldQuestsList, v92
  XLoot, v8.2-1
  XLootFrame, v8.2-1
  XLootGroup, v8.2-1
  XLootMaster, v8.2-1
  XLootMonitor, v8.2-1
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=ab0)

**Comment by smaitch** [comment]
Can you try the latest Grail from GitHub to see whether this "script ran too long" issue is better?

**Comment by smaitch** [comment]
Grail 110 is released.  It should fix this issue.
