### ISSUE TITLE
errors just downloaded.

### ISSUE THREAD

**Issue by panagiotis1962** [smaitch/Grail#141]
1x Grail\Grail-108.lua:8290: script ran too long
[string "@Grail\Grail-108.lua"]:8290: in function `NPCName'
[string "@Grail\Grail-108.lua"]:9719: in function `_RawNPCLocations'
[string "@Grail\Grail-108.lua"]:8242: in function `NPCLocations'
[string "@Grail\Grail-108.lua"]:9374: in function <Grail\Grail.lua:9362>
[string "=(tail call)"]: ?
[string "@Grail\Grail-108.lua"]:5883: in function `?'
[string "@Grail\Grail-108.lua"]:1386: in function `?'
[string "@Grail\Grail-108.lua"]:10580: in function `_Tooltip_OnEvent'
[string "@Grail\Grail-108.lua"]:11166: in function <Grail\Grail.lua:11166>

Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Grail\Grail.lua:9196
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Grail\Grail.lua:7067
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Grail\Grail.lua:9794
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Grail\Grail.lua:3390
 QuestLocationsAccept = <function> defined @Grail\Grail.lua:9354
 IsAvailable = <function> defined @Grail\Grail.lua:7049
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Grail\Grail.lua:6754
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Grail\Grail.lua:6782
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Grail\Grail.lua:5187
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Grail\Grail.lua:8463
 _MarkQuestType = <function> defined @Grail\Grail.lua:5556
 receivedCalendarUpdateEventList = false
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Grail\Grail.lua:9525
 _ProcessServerBackup = <function> defined @Grail\Grail.lua:8885
 bitMaskQuestVariableLevel = 4278190080
 MeetsRequirementGroup = <function> defined @Grail\Grail.lua:8045
 _EvaluateCodeAsPrerequisite = <function> defined @Grail\Grail.lua:6071
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Grail\Grail.lua:8130
 DoesNPCExist = <function> defined @Grail\Grail.lua:6036
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Grail\Grail.lua:3756
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Grail\Grail.lua:8316
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Grail\Grail.lua:3218
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Grail\Grail.lua:7612
 _HandleEventAchievementEarned = <function> defined @Grail\Grail.lua:6749
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 16384
 _ReputationExceeds = <function> defined @Grail\Grail.lua:9982
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = true
 LearnObjectName = <function> defined @Grail\Grail.lua:7538
 _ContainsAliasNPC = <function> defined @Grail\Grail.lua:5777
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Grail\Grail.lua:10081
 QuestBreadcrumbs = <function> defined @Grail\Grail.lua:9190
 NPCName = <function> defined @Grail\Grail.lua:8268
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Grail\Grail.lua:10628
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 _FactionsFromQuestGivers = <function> defined @Grail\Grail.lua:7947
 QuestOnAcceptCompletes = <function> defined @Grail\Grail.lua:9537
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 celebratingHolidayCache = <table> {
 }
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Grail\Grail.lua:7101
 bitMaskCanGetUnused8 = 4194304
 bitMaskCanGetUnused15 = 1073741824
 MeetsRequirementGroupPossibleToComplete = <function> defined @Grail\Grail.lua:8073
 questReputations = <table> {
 }
 _AddThreatQues

**Comment by panagiotis1962** [comment]
and this one

1x Grail\Grail-108.lua:3642: attempt to index field '?' (a nil value)
[string "@Grail\Grail-108.lua"]:3642: in function `_LearnWorldQuest'
[string "@Grail\Grail-108.lua"]:3513: in function `_AddWorldQuests'
[string "@Grail\Grail-108.lua"]:2075: in function `?'
[string "@Grail\Grail-108.lua"]:10580: in function `_Tooltip_OnEvent'
[string "@Grail\Grail-108.lua"]:11166: in function <Grail\Grail.lua:11166>

Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Grail\Grail.lua:9196
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Grail\Grail.lua:7067
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Grail\Grail.lua:9794
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Grail\Grail.lua:3390
 QuestLocationsAccept = <function> defined @Grail\Grail.lua:9354
 IsAvailable = <function> defined @Grail\Grail.lua:7049
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Grail\Grail.lua:6754
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Grail\Grail.lua:6782
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Grail\Grail.lua:5187
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Grail\Grail.lua:8463
 _MarkQuestType = <function> defined @Grail\Grail.lua:5556
 receivedCalendarUpdateEventList = true
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Grail\Grail.lua:9525
 _ProcessServerBackup = <function> defined @Grail\Grail.lua:8885
 bitMaskQuestVariableLevel = 4278190080
 MeetsRequirementGroup = <function> defined @Grail\Grail.lua:8045
 _EvaluateCodeAsPrerequisite = <function> defined @Grail\Grail.lua:6071
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Grail\Grail.lua:8130
 DoesNPCExist = <function> defined @Grail\Grail.lua:6036
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Grail\Grail.lua:3756
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Grail\Grail.lua:8316
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Grail\Grail.lua:3218
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Grail\Grail.lua:7612
 _HandleEventAchievementEarned = <function> defined @Grail\Grail.lua:6749
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 16384
 _ReputationExceeds = <function> defined @Grail\Grail.lua:9982
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = true
 LearnObjectName = <function> defined @Grail\Grail.lua:7538
 _ContainsAliasNPC = <function> defined @Grail\Grail.lua:5777
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Grail\Grail.lua:10081
 QuestBreadcrumbs = <function> defined @Grail\Grail.lua:9190
 NPCName = <function> defined @Grail\Grail.lua:8268
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Grail\Grail.lua:10628
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 _FactionsFromQuestGivers = <function> defined @Grail\Grail.lua:7947
 QuestOnAcceptCompletes = <function> defined @Grail\Grail.lua:9537
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 celebratingHolidayCache = <table> {
 }
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Grail\Grail.lua:7101
 bitMaskCanGetUnused8 = 4194304
 bitMaskCanGetUnused15 = 1073741824
 MeetsRequirementGroupPossibleToComplete = <function> defined @Grail\Grail.lua:8073
 questReputations = <table> {
 }
 _AddThreatQuest

**Comment by smaitch** [comment]
Can you download the latest Grail from GitHub and see if that is better?

**Comment by panagiotis1962** [comment]
NP did that and still getting this 
1x Grail\Grail-109.lua:3649: attempt to index field '?' (a nil value)
[string "@Grail\Grail-109.lua"]:3649: in function `_LearnWorldQuest'
[string "@Grail\Grail-109.lua"]:3519: in function `_AddWorldQuests'
[string "@Grail\Grail-109.lua"]:2078: in function `?'
[string "@Grail\Grail-109.lua"]:10588: in function `_Tooltip_OnEvent'
[string "@Grail\Grail-109.lua"]:11174: in function <Grail\Grail.lua:11174>

Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Grail\Grail.lua:9204
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Grail\Grail.lua:7075
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Grail\Grail.lua:9802
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Grail\Grail.lua:3393
 QuestLocationsAccept = <function> defined @Grail\Grail.lua:9362
 IsAvailable = <function> defined @Grail\Grail.lua:7057
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Grail\Grail.lua:6762
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Grail\Grail.lua:6790
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Grail\Grail.lua:5195
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Grail\Grail.lua:8471
 _MarkQuestType = <function> defined @Grail\Grail.lua:5564
 receivedCalendarUpdateEventList = true
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Grail\Grail.lua:9533
 _ProcessServerBackup = <function> defined @Grail\Grail.lua:8893
 bitMaskQuestVariableLevel = 4278190080
 MeetsRequirementGroup = <function> defined @Grail\Grail.lua:8053
 _EvaluateCodeAsPrerequisite = <function> defined @Grail\Grail.lua:6079
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Grail\Grail.lua:8138
 DoesNPCExist = <function> defined @Grail\Grail.lua:6044
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Grail\Grail.lua:3764
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Grail\Grail.lua:8324
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Grail\Grail.lua:3221
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Grail\Grail.lua:7620
 _HandleEventAchievementEarned = <function> defined @Grail\Grail.lua:6757
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 16384
 _ReputationExceeds = <function> defined @Grail\Grail.lua:9990
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = true
 LearnObjectName = <function> defined @Grail\Grail.lua:7546
 _ContainsAliasNPC = <function> defined @Grail\Grail.lua:5785
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Grail\Grail.lua:10089
 QuestBreadcrumbs = <function> defined @Grail\Grail.lua:9198
 NPCName = <function> defined @Grail\Grail.lua:8276
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Grail\Grail.lua:10636
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 _FactionsFromQuestGivers = <function> defined @Grail\Grail.lua:7955
 QuestOnAcceptCompletes = <function> defined @Grail\Grail.lua:9545
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 celebratingHolidayCache = <table> {
 }
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Grail\Grail.lua:7109
 bitMaskCanGetUnused8 = 4194304
 bitMaskCanGetUnused15 = 1073741824
 MeetsRequirementGroupPossibleToComplete = <function> defined @Grail\Grail.lua:8081
 questReputations = <table> {
 }
 _AddThreatQuest

**Comment by smaitch** [comment]
I just uploaded another Grail which should handle the _LearnWorldQuest issue.

**Comment by smaitch** [comment]
Can you test the latest version of Grail from GitHub to see whether the "script ran too long" issue is better?

**Comment by smaitch** [comment]
Grail 110 is released.  This should avoid this issue.
