### ISSUE TITLE
lua error on launch

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#142]
Message: Interface\AddOns\Grail\Grail.lua:3642: attempt to index field '?' (a nil value)
Time: Fri Feb 28 09:50:53 2020
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:3642: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\Grail\Grail.lua"]:3642: in function `_LearnWorldQuest'
[string "@Interface\AddOns\Grail\Grail.lua"]:3513: in function `_AddWorldQuests'
[string "@Interface\AddOns\Grail\Grail.lua"]:2075: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:10580: in function `_Tooltip_OnEvent'
[string "@Interface\AddOns\Grail\Grail.lua"]:11166: in function <Interface\AddOns\Grail\Grail.lua:11166>

Locals: self = <table> {
 QuestBreadcrumbsFor = <function> defined @Interface\AddOns\Grail\Grail.lua:9196
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Interface\AddOns\Grail\Grail.lua:7067
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Interface\AddOns\Grail\Grail.lua:9794
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Interface\AddOns\Grail\Grail.lua:3390
 QuestLocationsAccept = <function> defined @Interface\AddOns\Grail\Grail.lua:9354
 IsAvailable = <function> defined @Interface\AddOns\Grail\Grail.lua:7049
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Interface\AddOns\Grail\Grail.lua:6754
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Interface\AddOns\Grail\Grail.lua:6782
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:5187
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:8463
 _MarkQuestType = <function> defined @Interface\AddOns\Grail\Grail.lua:5556
 receivedCalendarUpdateEventList = true
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Interface\AddOns\Grail\Grail.lua:9525
 _ProcessServerBackup = <function> defined @Interface\AddOns\Grail\Grail.lua:8885
 bitMaskQuestVariableLevel = 4278190080
 MeetsRequirementGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:8045
 _EvaluateCodeAsPrerequisite = <function> defined @Interface\AddOns\Grail\Grail.lua:6071
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Interface\AddOns\Grail\Grail.lua:8130
 DoesNPCExist = <function> defined @Interface\AddOns\Grail\Grail.lua:6036
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Interface\AddOns\Grail\Grail.lua:3756
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Interface\AddOns\Grail\Grail.lua:8316
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Interface\AddOns\Grail\Grail.lua:3218
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Interface\AddOns\Grail\Grail.lua:7612
 _HandleEventAchievementEarned = <function> defined @Interface\AddOns\Grail\Grail.lua:6749
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 8192
 _ReputationExceeds = <function> defined @Interface\AddOns\Grail\Grail.lua:9982
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = true
 LearnObjectName = <function> defined @Interface\AddOns\Grail\Grail.lua:7538
 _ContainsAliasNPC = <function> defined @Interface\AddOns\Grail\Grail.lua:5777
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Interface\AddOns\Grail\Grail.lua:10081
 QuestBreadcrumbs = <function> defined @Interface\AddOns\Grail\Grail.lua:9190
 NPCName = <function> defined @Interface\AddOns\Grail\Grail.lua:8268
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Interfa

**Comment by smaitch** [comment]
Please try the latest Grail on GitHub to see whether it fixes this _LearnWorldQuest issue.

**Comment by Schtenk** [comment]
Latest Grail on Github seems to have fixed this issue for me

**Comment by Wyr3d** [comment]
I believe that is the latest version. I have the latest version installed according to the Twitch app, anyway and I still get LUA errors like this one:

Message: Interface\AddOns\Grail\Grail.lua:3642: attempt to index field '?' (a nil value)
Time: Thu Mar 12 21:00:52 2020
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:3642: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Grail\Grail.lua"]:3642: in function `_LearnWorldQuest'
[string "@Interface\AddOns\Grail\Grail.lua"]:3513: in function `_AddWorldQuests'
[string "@Interface\AddOns\Grail\Grail.lua"]:2075: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:10580: in function `_Tooltip_OnEvent'
[string "@Interface\AddOns\Grail\Grail.lua"]:11166: in function <Interface\AddOns\Grail\Grail.lua:11166>

Locals:

**Comment by smaitch** [comment]
Twitch is installing version 108.  GitHub has on it what will become 109 (which should have the fix).  Therefore, if you manually install the GitHub version I would think the issue should be gone.

**Comment by smaitch** [comment]
Closing this since others have indicated the GitHub version works for this problem.
