### ISSUE TITLE
Classic - am I reading this right?

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#144]
You have, as an example

G[8404]='K029257 L020 N029 A:15351 T:15351 P:8372,8399,8400,8401,8402,8403'
G[8405]='K039257 L030 N039 A:15351 T:15351 P:8372,8399,8400,8401,8402,8403'
G[8406]='K049257 L040 N049 A:15351 T:15351 P:8372,8399,8400,8401,8402,8403'
G[8407]='K059257 L050 N059 A:15351 T:15351 P:8372,8399,8400,8401,8402,8403'

Should the Ns be Ms?

**Comment by smaitch** [comment]
I don't think any of the Classic quests have been marked with M codes.  In fact, I think some of the M codes in Retail are going to be removed based on some others' findings.  In any case, the automated process is how the K L and N codes are derived, so I would blame that on these values.

**Comment by Nerillida** [comment]
The Warsong Gulch are in level ranges, but I don't suppose it matters that much as they will no be confusing as they are just alternatives. Some of the retail still have level requirements that M codes look after, admittedly far fewer. Lat's hope they do disappear.
