### ISSUE TITLE
Classic, Darkmoon Faire

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#145]
Elwyn Forest is still in preparation but quests showing on map and in Wholly's list.
EU, 2020 03 08 22:55 and was also showing some hours ago.

**Comment by smaitch** [comment]
I believe the issue was with:
			local weekdayToUse = (weekday == 0) and 8 or weekday
which really should have compared to 1 instead of 0.  This would allow the normal Darkmoon Faire availability to be on Sunday instead of Monday as it should.  This is corrected for the next Grail.

**Comment by smaitch** [comment]
The latest Grail has been pushed with this change.

**Comment by Nerillida** [comment]
Thanks, I see it.
