### ISSUE TITLE
Retail - Quest has wrong factions

### ISSUE THREAD

**Issue by Zardilann** [smaitch/Grail#152]
Quest ID 13506 is wrongly marked available for Horde.

**Comment by Nerillida** [comment]
https://www.wowhead.com/npc=32963/lieutenant-morra-starbreeze

Turn in is Alliance onlyNPC.

**Comment by smaitch** [comment]
The next version of Grail will include the quick fix for this:

G[13506]='fA K0000 L010 N060 A:100044979 T:32963'
