### ISSUE TITLE
Retail - Quest Missing Prerequisite

### ISSUE THREAD

**Issue by Zardilann** [smaitch/Grail#155]
Tried to pick up https://www.wowhead.com/quest=28423/warlocks-have-the-neatest-stuff (Horde version) as it was marked available. Reading the comments, it requires https://www.wowhead.com/quest=28422/the-sand-the-cider-and-the-orb (Horde version) and after picking that up, I could get the quest.

Not sure if https://www.wowhead.com/quest=28181/warlocks-have-the-neatest-stuff (Alliance version) is marked as requiring https://www.wowhead.com/quest=28180/the-sand-the-cider-and-the-orb (Alliance version).

**Comment by smaitch** [comment]
Grail is being updated for the next release with the following changes needed for Horde.  No changes needed to be made for Alliance:

G[28423]='FH K0000 L040 N060 A:14437 T:14437 P:28422'
G[28424]='FH K0000 L040 N060 A:14437 T:14437 P:28422'
