### ISSUE TITLE
Retail - Wrong race requirement

### ISSUE THREAD

**Issue by Zardilann** [smaitch/Grail#156]
https://www.wowhead.com/quest=51485/for-the-horde

It's labeled as being available to Blood Elves, but matches the similar For the Horde quests for the other allied races, and the text shows that it is for the Mag'har orcs.

Same thing with https://www.wowhead.com/quest=53502/stranger-in-a-strange-land being available for all races, when it's just for the Mag'har.

**Comment by smaitch** [comment]
Grail has been updated for the next release.
