### ISSUE TITLE
Retail - Missing requirement

### ISSUE THREAD

**Issue by Zardilann** [smaitch/Grail#157]
https://www.wowhead.com/quest=28723/priestess-of-the-moon requires https://www.wowhead.com/quest=28715/demonic-thieves before it's available.

**Comment by Nerillida** [comment]
G[28723]='K0000 L001 N060 A:2079 T:49479 P:28714'

should be

G[28723]='K0000 L001 N060 A:2079 T:49479 P:28714+ 28715'

checked

**Comment by smaitch** [comment]
The next version of Grail has this change.
