### ISSUE TITLE
LUA Error on Log In

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#158]
This used to pop up once ever so often, but has been happening quite often now:

Message: Interface\AddOns\Grail\Grail.lua:8290: script ran too long
Time: Sun Mar 22 02:29:41 2020
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:8290: script ran too long
[string "=[C]"]: ?
[string "@Interface\AddOns\Grail\Grail.lua"]:8290: in function `NPCName'
[string "@Interface\AddOns\Grail\Grail.lua"]:9719: in function `_RawNPCLocations'
[string "@Interface\AddOns\Grail\Grail.lua"]:8242: in function `NPCLocations'
[string "@Interface\AddOns\Grail\Grail.lua"]:9374: in function <Interface\AddOns\Grail\Grail.lua:9362>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Grail\Grail.lua"]:5883: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:1386: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:10580: in function `_Tooltip_OnEvent'
[string "@Interface\AddOns\Grail\Grail.lua"]:11166: in function <Interface\AddOns\Grail\Grail.lua:11166>

Locals:

**Comment by smaitch** [comment]
This is a duplication of https://github.com/smaitch/Grail/issues/154
