### ISSUE TITLE
Retail - Missing class requirement

### ISSUE THREAD

**Issue by Zardilann** [smaitch/Grail#162]
The following quests are missing Mage as a class requirement:

https://www.wowhead.com/quest=42166/what-is-going-on-here
https://www.wowhead.com/quest=42435/prepare-to-be-assimilated
https://www.wowhead.com/quest=42171/final-exit
https://www.wowhead.com/quest=42149/some-knowledge-shouldnt-be-shared
https://www.wowhead.com/quest=42206/the-next-level-has-arrived

**Comment by smaitch** [comment]
The next version of Grail has these marked.
