### ISSUE TITLE
"We Need An Outpost" made the rest of the Loremasters orange.

### ISSUE THREAD

**Issue by puggan** [smaitch/Grail#17]
Turning in the quest "We Need An Outpost"(35063) turn all red-loremaster quests into orange-loremaster quests.

![screen shot 2017-09-27 at 18 26 59](https://user-images.githubusercontent.com/866668/30925313-b6dd5154-a3b1-11e7-9508-ca1a86c5d812.png)

**Comment by smaitch** [comment]
The quests appear red when there are prerequisites that need to be fulfilled.  As one fulfills requirements, other quests will change from red to different colors.  Yellow quests are normal ones, and orange quests are ones that are marked as legendary.  Some of the legendary quests are the old ones given by the black dragon, and a lot of them are for the artifact weapons in Legion.

**Comment by puggan** [comment]
Sorry, red=Need orerequisites => orange=Unobtainable
diging around, and quest (35049) Lumbermill looks to be to suspisus one.
but i keep diging abit more.

**Comment by puggan** [comment]
Grail-Achievements/Grail-Achievements.lua, row 6813
```
G[35137]={508923}        -- The Sparring Arena
```

I didn't select the Sparring Arena

**Comment by puggan** [comment]
"Strike While the Iron is Hot" is one of the requirements for achivment 508923:

But it looks like it sugesting that i do the Horde achivment/quests?

Without loremaster filter, showing all 4 versions, but only one is red:
![screen shot 2017-09-27 at 19 29 15](https://user-images.githubusercontent.com/866668/30928008-8f90b0ec-a3ba-11e7-9f73-0c9640fc0a14.png)

With loremaster filter, showing only 2 versions, both is for horde:
![screen shot 2017-09-27 at 19 29 46](https://user-images.githubusercontent.com/866668/30928026-9ddc11e6-a3ba-11e7-846c-f756ca59a253.png)

**Comment by puggan** [comment]
Grail-Achievements/Grail-Achievements.lua
row 7009 - 7010
```
Grail.indexedQuests[achievement] = newTable
Grail.loremasterQuests[achievementsToZoneMapping[achievement]] = newTable
```

For Zone 949, there is 3 achivments: 508923, 508924, 509607

for each of thous 3, the code above adds a tale to indexedQuests at the achivment-id as position,
and then tries to add it to the loremasterQuests at the zone-id as position = 949.

all 3 achivments wirtes to loremasterQuests[949], replacing it, insted of merging them.

**Comment by puggan** [comment]
As I have no ide how to merge the tables, i Moved the other 2 achivments to another zone, and it solved the problem.

So same promlem as in Issue #15, so closing thisone.
