### ISSUE TITLE
Quest mismatch 57445 accepted but log has 0

### ISSUE THREAD

**Issue by Thrumbar** [smaitch/Grail#170]

**Comment by smaitch** [comment]
Can you attach you Grail.lua saved variables file so Grail can be updated with this information?

**Comment by Mythos** [comment]
Hi there, I've attached a Grail.lua file which contains this quest. See #173

**Comment by smaitch** [comment]
The Grail.lua file has been processed for this information (though there was nothing about the acceptance of the quest in it).
