### ISSUE TITLE
Hellfire Peninsula Quests: Wanted: orgmaster Krush 10809

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#172]
This quest appears to unlock the following:

10792 - Zeth'Gor must Burn
10813 - The Eyes of Grillock

These quests were not available when I first arrived in Spinebreaker Post, but became avaialbe after handing in this quest. Please note that I also handed in Preparing the Salve [9345] so this may also be a trigger for The Eyes of Grillock as I did not look in that direction before handing in both.

**Comment by smaitch** [comment]
The next release of Grail has been updated with this.
