### ISSUE TITLE
[8.3] Quest mismatches

### ISSUE THREAD

**Issue by Mythos** [smaitch/Grail#173]
Hey there,
when entering the Vale of Eternal Blossoms, I'm getting a warning about mismatches as those quests are not in the database yet.

![vale](https://user-images.githubusercontent.com/416568/78792492-76f28900-79b1-11ea-89ff-83c32738fcdf.png)

I've attached a zip archive containing multiple ```Grail.lua``` files (for 3 lvl 120 characters and the one saved in ```SavedVariables```)

[Grail.zip](https://github.com/smaitch/Grail/files/4450875/Grail.zip)

**Comment by yoshimo** [comment]
These quest ids correspond to active events like freeing a bound elemental and won't appear in the players questlog. You can ignore that warning.
More interesting are quests that get reported as missing

**Comment by Mythos** [comment]
Ah thanks for explaining, I don't have knowledge about the API, but I thought they are like World Quests as ```ls: Toasts``` is displaying them in the same way when they are completed. Same goes for Zygor which shows it in the right panel which normally contains World Quests.
With normal World Quests I've never gotten any warning from Grail, so I thought it might be helpful to report them. :-)

Hopefully my Grail.lua file is still helpful in any way. (de-DE locale)

**Comment by smaitch** [comment]
With the latest Grail the acceptance of quests has changed a bit so this type of warning message should be very much less frequent, and should only occur in very specific incidents.
