### ISSUE TITLE
Zangarmarsh Quest: Message to the Daggerfen [10118]

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#174]
This quest is locked until you have completed Impending Attack [9822] I don't know why, since Impending attack is an ogre quest, but it is. Grail has this avaiable from the get go, but it should be gated behind that quest.

Weirdly, both the WANTED: kill this mob quests are avaialble from the get-go despite one being an ogre boss and the other being a daggerfen boss. lol

**Comment by smaitch** [comment]
Grail has been updated for the next release.

G[10118]='FH L15440 A:18013 T:18013 P:9822'
