### ISSUE TITLE
Classic - Children's Week is active

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#178]
Classic - Children's Week is active - Wholly;Grail does not seem to realise.

**Comment by smaitch** [comment]
Do we have a way we can know what these are going to be for the next year so we can code them up?

**Comment by Nerillida** [comment]
I have no idea, I suppose Blizzard may publish the dates, but I have not seen this.

Who knows what we will have next year, Classic/TBC or what.

**Comment by Nerillida** [comment]
No longer relevant
