### ISSUE TITLE
Cultists among us (quest faction error)

### ISSUE THREAD

**Issue by xMukkhx** [smaitch/Grail#180]
Im horde and it says that the quest Cultist Among Us its for both factions but it's not, its only for Alliance
https://www.wowhead.com/quest=11920/cultists-among-us
Please fix. thank you

**Comment by xMukkhx** [comment]
quest ID 11920

**Comment by Nerillida** [comment]
Should be
--G[11790]='FA L14928 A:1187851 T:25298'	-- apparently no longer in game/available
G[11920]='fA L14928 A:1187851 T:25298 P:11789'	-- P needed, turn in Alliance friendly only

**Comment by smaitch** [comment]
Grail is updated for next release.
