### ISSUE TITLE
Orgrimmar Quest: Blown Away [29401]

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#181]
The pin for this quest is missing from the Orgrimmar map. The NPC is Jaga, his coords are 48/47

**Comment by Nerillida** [comment]
Confirm not showing on map , both quest and NPC are in the data files - NPC's location is good. The quest shows on Wholly's list.

**Comment by smaitch** [comment]
Changed the zone from 86 to 85 in the next Grail.
