### ISSUE TITLE
Tirasguard Sound Quest - Tearing at the Seams [55177] (Alliance)

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#182]
This quest is Tailoring only - it is currently showing as available for my char who is a Blacksmith/Miner

**Comment by Nerillida** [comment]
Similar quest of Horde side, 55188. Both are chains.

**Comment by smaitch** [comment]
The next Grail is updated with:
G[55177]='FA L30840 A:151137 T:704001 P:PT001 E32028'
G[55188]='FH L30840 P:PT001 E32028'

**Comment by Nerillida** [comment]
For 55177 see the chain  at 
https://www.wowhead.com/quest=55177/tearing-at-the-seams#comments
similar for other faction.
