### ISSUE TITLE
Error on low-level entering Hyjal

### ISSUE THREAD

**Issue by solitha** [smaitch/Grail#188]
During the summer festival I've been running my 60-70s around for heirloom upgrades and lots of levels. Each time one of them enters Hyjal (via personal flyer) I get the following error:

```
1x Grail\Grail-110.lua:3982: Usage: local powerLevel = C_AzeriteItem.GetPowerLevel(azeriteItemLocation)
[string "=[C]"]: in function `GetPowerLevel'
[string "@Grail\Grail-110.lua"]:3982: in function `AzeriteLevelMeetsOrExceeds'
[string "@Grail\Grail-110.lua"]:6340: in function `f'
[string "@Grail\Grail-110.lua"]:3798: in function `_AllEvaluateTrueS'
[string "@Grail\Grail-110.lua"]:3898: in function <Grail\Grail.lua:3879>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Grail\Grail-110.lua"]:7864: in function `MeetsPrerequisites'
[string "@Grail\Grail-110.lua"]:10436: in function `StatusCode'
[string "@Grail\Grail-110.lua"]:6475: in function `f'
[string "@Grail\Grail-110.lua"]:3798: in function `_AllEvaluateTrueS'
[string "@Grail\Grail-110.lua"]:3898: in function <Grail\Grail.lua:3879>
[string "=(tail call)"]: ?
[string "@Grail\Grail-110.lua"]:3815: in function `AncestorStatusCode'
[string "@Grail\Grail-110.lua"]:10438: in function `StatusCode'
[string "@Grail\Grail-110.lua"]:4346: in function `ClassificationOfQuestCode'
[string "@Wholly\Wholly-079.lua"]:1431: in function `_ClassifyQuestsInMap'
[string "@Wholly\Wholly-079.lua"]:1882: in function `_ForcePanelMapArea'
[string "@Wholly\Wholly-079.lua"]:4411: in function `UpdateQuestCaches'
[string "@Wholly\Wholly-079.lua"]:960: in function `?'
[string "@Wholly\Wholly-079.lua"]:2526: in function `_OnEvent'
[string "@Wholly\Wholly-079.lua"]:4427: in function <Wholly\Wholly.lua:4427>

Locals:
```
I don't know if the same thing happens with all <110 characters, but I wanted to be sure I submitted this because I'm on the last of the lowest characters who can reach the zone.

**Comment by Zathriam** [comment]
Been experiencing the exact same issue for quite a while now.
Every time I take the portal to Hyjal that shit pops up in the swatter.
I do not have the BfA expansion installed if that info is of any use.
---

Date: 2020-07-21 23:26:37
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Grail\Grail.lua line 3982:
   Usage: local powerLevel = C_AzeriteItem.GetPowerLevel(azeriteItemLocation)
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: GetPowerLevel()
   [string "@Grail\Grail.lua"]:3982: AzeriteLevelMeetsOrExceeds()
   [string "@Grail\Grail.lua"]:6340: f()
   [string "@Grail\Grail.lua"]:3798: _AllEvaluateTrueS()
   [string "@Grail\Grail.lua"]:3898:
      Grail\Grail.lua:3879
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "@Grail\Grail.lua"]:7864: MeetsPrerequisites()
   [string "@Grail\Grail.lua"]:10436: StatusCode()
   [string "@Grail\Grail.lua"]:6475: f()
   [string "@Grail\Grail.lua"]:3798: _AllEvaluateTrueS()
   [string "@Grail\Grail.lua"]:3898:
      Grail\Grail.lua:3879
   [string "=(tail call)"]: ?
   [string "@Grail\Grail.lua"]:3815: AncestorStatusCode()
   [string "@Grail\Grail.lua"]:10438: StatusCode()
   [string "@Grail\Grail.lua"]:4346: ClassificationOfQuestCode()
   [string "@Wholly\Wholly.lua"]:1431: _ClassifyQuestsInMap()
   [string "@Wholly\Wholly.lua"]:1882: _ForcePanelMapArea()
   [string "@Wholly\Wholly.lua"]:4411: UpdateQuestCaches()
   [string "@Wholly\Wholly.lua"]:960: ?()
   [string "@Wholly\Wholly.lua"]:2526: _OnEvent()
   [string "@Wholly\Wholly.lua"]:4427:
      Wholly\Wholly.lua:4427
Locals:

**Comment by solitha** [comment]
Seeing this new comment, I revisited this thing. It does seem to trigger on anyone without a Heart of Azeroth (I didn't go through all my characters). It triggers either on entering the zone OR opening the zone map. I do have BfA.

**Comment by smaitch** [comment]
Grail has been updated on GitHub to ensure the API exists before it is called.
