### ISSUE TITLE
Classic - prerequisite problem

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#190]
Quest 2501 hs the prerequisites
P:2500,PA210
this showed available in Wholly/map when 2500 had been turned in. The character did not have alchemy as a profession.
So I tried
P:2500+PA210
Still showed as available in Wholly/map.

Thanks

Additionally, character with neither quest prereq nor alchemy shows Unobtainable
Additionally, character with quest prereq not alchemy shows Available

**Comment by smaitch** [comment]
I think this has already been handled, as the requirements are now 2500+17+PA210, so unless you have already done both reagent runs and have the alchemy skill it should be unobtainable.
