### ISSUE TITLE
Classic - URGENT

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#204]
At the very least 
Please

			elseif 'Q' == holidayCode and self.existsClassic then
				-- Ahn'Q
				if 2020 == year and 7 >= month and day >= 29 then
					retval = true
				end

TBH
The conditionals for each material on each server being fulfilled/not fulfilled is probably best "ducked".

Ditto, when the war effort is finished, server by server.

I have put the above in my latest pull request. Also corrected some War Effort quests/NPCs.

**Comment by smaitch** [comment]
I have updated the detection of AQ holiday in my latest push.
