### ISSUE TITLE
Classic Quest 8851

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#207]
In your latest version, you have changed

G[8851]='SP HQ L1247999 A:15700 T:15700 E31727'
G[8851]='SP HQ L1247763 A:15700 T:15700 P:8792 E31727'

None of the quests for turn ins etc depend on any of the variants of The Horde Needs Your Help!
The alliance side is the same.

**Comment by smaitch** [comment]
It looks like you actually made this change on Nov 25 2019.

**Comment by Nerillida** [comment]
Must be a typo if I added the prerequisite.

**Comment by Nerillida** [comment]
I have removed this pre-requisite in my version which I will Pull request soon.
