### ISSUE TITLE
Classic error

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#209]
In your latest version

The class/race specific/profession quests are not showing

Date: 2020-08-12 16:46:15
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Grail\Grail.lua line 5415:
   attempt to index field '?' (a nil value)
Debug:
   Grail\Grail.lua:5415: _CodeAllFixed()
   Grail\Grail.lua:5961: ?()
   Grail\Grail.lua:1413: ?()
   Grail\Grail.lua:10774: _Tooltip_OnEvent()
   Grail\Grail.lua:11360:
      Grail\Grail.lua:11360
Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Interface\AddOns\Grail\Grail.lua:9381
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Interface\AddOns\Grail\Grail.lua:7232
 totalRawNPCLocations = 9.498670
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Interface\AddOns\Grail\Grail.lua:9988
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Interface\AddOns\Grail\Grail.lua:3442
 QuestLocationsAccept = <function> defined @Interface\AddOns\Grail\Grail.lua:9539
 IsAvailable = <function> defined @Interface\AddOns\Grail\Grail.lua:7214
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Interface\AddOns\Grail\Grail.lua:6904
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Interface\AddOns\Grail\Grail.lua:6932
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:5251
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:8640
 _MarkQuestType = <function> defined @Interface\AddOns\Grail\Grail.lua:5638
 receivedCalendarUpdateEventList = false
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Interface\AddOns\Grail\Grail.lua:9713
 _ProcessServerBackup = <function> defined @Interface\AddOns\Grail\Grail.lua:9070
 bitMaskQuestVariableLevel = 255
 MeetsRequirementGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:8221
 _EvaluateCodeAsPrerequisite = <function> defined @Interface\AddOns\Grail\Grail.lua:6161
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Interface\AddOns\Grail\Grail.lua:8306
 DoesNPCExist = <function> defined @Interface\AddOns\Grail\Grail.lua:6126
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Interface\AddOns\Grail\Grail.lua:3813
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Interface\AddOns\Grail\Grail.lua:8493
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Interface\AddOns\Grail\Grail.lua:3257
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Interface\AddOns\Grail\Grail.lua:7787
 _HandleEventAchievementEarned = <function> defined @Interface\AddOns\Grail\Grail.lua:6899
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 16384
 _ReputationExceeds = <function> defined @Interface\AddOns\Grail\Grail.lua:10176
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = false
 LearnObjectName = <function> defined @Interface\AddOns\Grail\Grail.lua:7712
 _ContainsAliasNPC = <function> defined @Interface\AddOns\Grail\Grail.lua:5859
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Interface\AddOns\Grail\Grail.lua:10275
 QuestBreadcrumbs = <function> defined @Interface\AddOns\Grail\Grail.lua:9375
 NPCName = <function> defined @Interface\AddOns\Grail\Grail.lua:8445
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Interface\AddOns\Grail\Grail.lua:10822
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 _FactionsFromQuestGivers = <function> defined @Interface\AddOns\Grail\Grail.lua:8123
 QuestOnAcceptCompletes = <function> defined @Interface\AddOns\Grail\Grail.lua:9725
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 celebratingHolidayCache = <table> {
 }
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:7266
 bitMaskCanGetUnused8 = 4194304
 bitMaskCanGetUnused15 = 1073741824
 MeetsRequirementGroupPossibleToComplete = <function> defined @Interface\AddOns\Grail\Grail.lua:8249
 questReputations = 
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  auccheapsearcher, v20190917r3
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BadBoy, vv1-classic
  BadBoyCCleaner, vv8.2.0
  BadBoyGuilded, vv8.2.0
  BasicChatMods, vv4-classic
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.05
  BrokerPortals, v1.11.1
  ClassicAutoDismount, v1.01
  ClassicCastbars, vv1.3.9
  ClassicCastbarsOptions, v
  ClassicSpellActivations, v
  ClassTrainerPlus, v0.7-beta
  CTBarMod, v8.3.0.9
  CTBuffMod, v8.3.0.9
  CTCore, v8.3.0.9
  CTLibrary, v8.3.0.9
  CTMailMod, v8.3.0.7
  CTMapMod, v8.3.0.8
  CTPartyBuffs, v8.2.5.6
  CTUnitFrames, v8.3.0.9
  DidIDoIt, v1.2.0
  EMAClassic, vv1.13.4-Release-v0.9(121029)
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtVendorUIClassic, v1.0.4
  FloAspectBar, v
  FloTotemBar, v
  GatherMate2, v1.45.4
  GlobalIgnoreList, v1.13.2
  Grail, v111
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v33302
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v33302
  GSE, v2.5.5
  GSEGUI, v2.5.5
  GSELDB, v2.5.5
  Informant, v8.2.6508 (SwimmingSeadragon)
  ISBoxer, v1.0
  LetMeCast, v1.3
  MageButtons, v1.0
  Mapster, v1.8.5
  Misspelled, v1.7.7
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  OmniCC, v8.2.4
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v6.0.4
  QuestLogEx, v1.2
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  SpamThrottleClassic, vv4.0c
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TFTB, v1.10
  TitanClassic, v1.2.4.11305
  TitanClassicAmmo, v1.2.4.11305
  TitanClassicBag, v1.2.4.11305
  TitanClassicClock, v1.2.4.11305
  TitanClassicGold, v1.2.4.11305
  TitanClassicLocation, v1.2.4.11305
  TitanClassicLootType, v1.2.4.11305
  TitanClassicPerformance, v1.2.4.11305
  TitanClassicRegen, v1.2.4.11305
  TitanClassicRepair, v1.2.4.11305
  TitanClassicVolume, v1.2.4.11305
  TitanClassicXP, v1.2.4.11305
  WhatsTraining, v1.8.7
  Wholly, v079
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=962)

**Comment by smaitch** [comment]
It turns out that the RG code added from automatic processing I failed to remove before now.
