### ISSUE TITLE
[Retail] Error on load -  attempt to index field 'rawLocations' (a nil value)

### ISSUE THREAD

**Issue by LadyEleora** [smaitch/Grail#211]
I've downloaded the most recent version of Grail but still receive this error on load.

Message: Interface\AddOns\Grail\Grail.lua:9772: attempt to index field 'rawLocations' (a nil value)
Time: Sat Aug 15 13:05:32 2020
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:9772: attempt to index field 'rawLocations' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Grail\Grail.lua"]:9772: in function `_RawNPCLocations'
[string "@Interface\AddOns\Grail\Grail.lua"]:8288: in function `NPCLocations'
[string "@Interface\AddOns\Grail\Grail.lua"]:9432: in function `_QuestLocations'
[string "@Interface\AddOns\Grail\Grail.lua"]:9411: in function `QuestLocationsAccept'
[string "@Interface\AddOns\Grail\Grail.lua"]:5921: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:1398: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:10644: in function `_Tooltip_OnEvent'
[string "@Interface\AddOns\Grail\Grail.lua"]:11230: in function <Interface\AddOns\Grail\Grail.lua:11230>

Locals:

**Comment by smaitch** [comment]
This should be fixed with the latest Grail.
