### ISSUE TITLE
[Retail] Quests 11532, 11538, 11539 and 11542

### ISSUE THREAD

**Issue by xoomoh** [smaitch/Grail#222]
Daily quests. Not regular.

https://www.wowhead.com/quest=11532/distraction-at-the-dead-scar
https://www.wowhead.com/quest=11538/the-battle-for-the-suns-reach-armory
https://www.wowhead.com/quest=11539/taking-the-harbor
https://www.wowhead.com/quest=11542/intercept-the-reinforcements

**Comment by smaitch** [comment]
The next version of Grail is updated with this information.
