### ISSUE TITLE
LUA Errors after latest update for Wholly & Grail

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#232]
Grail still appears to have some issues. This popped up while I was entering Ashenvale from Mor'shan Ramparts. No idea why

Message: Interface\AddOns\Grail\Grail.lua:8791: Usage: GetGarrisonInfo(garrisonType)
Time: Thu Oct 15 11:04:12 2020
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:8791: Usage: GetGarrisonInfo(garrisonType)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetGarrisonInfo'
[string "@Interface\AddOns\Grail\Grail.lua"]:8791: in function `_PhaseMatches'
[string "@Interface\AddOns\Grail\Grail.lua"]:6426: in function `f'
[string "@Interface\AddOns\Grail\Grail.lua"]:3728: in function `_AllEvaluateTrueS'
[string "@Interface\AddOns\Grail\Grail.lua"]:3828: in function <Interface\AddOns\Grail\Grail.lua:3809>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Grail\Grail.lua"]:8111: in function `MeetsPrerequisites'
[string "@Interface\AddOns\Grail\Grail.lua"]:10784: in function `StatusCode'
[string "@Interface\AddOns\Grail\Grail.lua"]:6603: in function `f'
[string "@Interface\AddOns\Grail\Grail.lua"]:3728: in function `_AllEvaluateTrueS'
...
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Grail\Grail.lua"]:3745: in function `AncestorStatusCode'
[string "@Interface\AddOns\Grail\Grail.lua"]:10786: in function `StatusCode'
[string "@Interface\AddOns\Grail\Grail.lua"]:4283: in function `ClassificationOfQuestCode'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:1434: in function `_ClassifyQuestsInMap'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:1885: in function `_ForcePanelMapArea'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:4417: in function `UpdateQuestCaches'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:963: in function `?'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:2532: in function `_OnEvent'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:4433: in function <Interface\AddOns\Wholly\Wholly.lua:4433>

Locals:

**Comment by yoshimo** [comment]
Line ~8624 In Grail.lua needs to be
`currentPhase = C_Garrison.GetGarrisonInfo(Enum.GarrisonType.Type_6_0) `
some things changed to enums in the SL Patch.
Might still be missing in the curren release

**Comment by smaitch** [comment]
I just pushed an update to GitHub that redefines the old enum in an attempt to get this to work properly.

**Comment by smaitch** [comment]
Grail 112 is now released with this change.
