### ISSUE TITLE
Grail\Grail-111.lua:3854: attempt to call global 'GetCurrencyInfo' (a nil value)

### ISSUE THREAD

**Issue by MarkusSB** [smaitch/Grail#236]
Error:

9x Grail\Grail-111.lua:3854: attempt to call global 'GetCurrencyInfo' (a nil value)
[string "@Grail\Grail-111.lua"]:3854: in function `ArtifactKnowledgeLevel'
[string "@Grail\Grail-111.lua"]:6453: in function `f'
[string "@Grail\Grail-111.lua"]:3728: in function `_AllEvaluateTrueS'
[string "@Grail\Grail-111.lua"]:3828: in function <Grail\Grail.lua:3809>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Grail\Grail-111.lua"]:8111: in function `MeetsPrerequisites'
[string "@Grail\Grail-111.lua"]:10784: in function `StatusCode'
[string "@Grail\Grail-111.lua"]:6603: in function `f'
[string "@Grail\Grail-111.lua"]:3728: in function `_AllEvaluateTrueS'
[string "@Grail\Grail-111.lua"]:3828: in function <Grail\Grail.lua:3809>
[string "=(tail call)"]: ?
...
[string "=(tail call)"]: ?
[string "@Grail\Grail-111.lua"]:3745: in function `AncestorStatusCode'
[string "@Grail\Grail-111.lua"]:10786: in function `StatusCode'
[string "@Grail\Grail-111.lua"]:4283: in function `ClassificationOfQuestCode'
[string "@Wholly\Wholly-080.lua"]:1434: in function `_ClassifyQuestsInMap'
[string "@Wholly\Wholly-080.lua"]:1885: in function `_ForcePanelMapArea'
[string "@Wholly\Wholly-080.lua"]:4417: in function `UpdateQuestCaches'
[string "@Wholly\Wholly-080.lua"]:963: in function `?'
[string "@Wholly\Wholly-080.lua"]:2532: in function `_OnEvent'
[string "@Wholly\Wholly-080.lua"]:4433: in function <Wholly\Wholly.lua:4433>

Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Grail\Grail.lua:9571
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Grail\Grail.lua:7343
 totalRawNPCLocations = 190.347200
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Grail\Grail.lua:10178
 bitMaskCompleted = 1
 tooltip = com_mithrandir_grailTooltip {
 }
 QuestLocationsAccept = <function> defined @Grail\Grail.lua:9729
 IsAvailable = <function> defined @Grail\Grail.lua:7325
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Grail\Grail.lua:7015
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Grail\Grail.lua:7043
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Grail\Grail.lua:5330
 reputationFriends = <table> {
 }
 questsLoremaster = <table> {
 }
 NPC_TYPE_BY = "BY"
 GetNPCInformation = <function> defined @Grail\Grail.lua:6867
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Grail\Grail.lua:8820
 _MarkQuestType = <function> defined @Grail\Grail.lua:5717
 receivedCalendarUpdateEventList = true
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Grail\Grail.lua:9903
 _ProcessServerBackup = <function> defined @Grail\Grail.lua:9260
 bitMaskQuestVariableLevel = 255
 MeetsRequirementGroup = <function> defined @Grail\Grail.lua:8352
 _EvaluateCodeAsPrerequisite = <function> defined @Grail\Grail.lua:6240
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Grail\Grail.lua:8437
 DoesNPCExist = <function> defined @Grail\Grail.lua:6205
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Grail\Grail.lua:3705
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Grail\Grail.lua:8624
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Grail\Grail.lua:3237
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Grail\Grail.lua:7902
 _HandleEventAchievementEarned = <function> defined @Grail\Grail.lua:7010
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 8192
 _ReputationExceeds = <function> defined @Grail\Grail.lua:10366
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = true
 _ContainsAliasNPC = <function> defined @Grail\Grail.lua:5938
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Grail\Grail.lua:10465
 QuestBreadcrumbs = <function> defined @Grail\Grail.lua:9565
 _UpdateWorldQuestSelfNPC = <function> defined @Grail\Grail.lua:4491
 NPCName = <function> defined @Grail\Grail.lua:8576
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Grail\Grail.lua:11040
 _CleanDatabaseLearnedObjectName = <function> defined @Grail\Grail.lua:4433
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 _FactionsFromQuestGivers = <function> defined @Grail\Grail.lua:8270
 QuestOnAcceptCompletes = <function> defined @Grail\Grail.lua:9915
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 celebratingHolidayCache = <table> {
 }
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Grail\Grail.lua:7377
 bitMaskCanGetUnused8

**Comment by smaitch** [comment]
A new version of Grail has been pushed to GitHub that should fix this issue.
