### ISSUE TITLE
Still getting 4 LUA errors when turning on Grail

### ISSUE THREAD

**Issue by Houseofkannan** [smaitch/Grail#238]
This one, the count keeps spinning up into infinity. This also prevents you from going into the menu and turning the game off...it requires you to ALT-F4 to close the game.

> Message: Interface\AddOns\Grail\Grail.lua:10092: attempt to index field 'rawLocations' (a nil value)
> Time: Mon Oct 19 11:19:31 2020
> Count: 1718
> Stack: Interface\AddOns\Grail\Grail.lua:10092: attempt to index field 'rawLocations' (a nil value)
> [string "=[C]"]: ?
> [string "@Interface\AddOns\Grail\Grail.lua"]:10092: in function `_RawNPCLocations'
> [string "@Interface\AddOns\Grail\Grail.lua"]:8549: in function `NPCLocations'
> [string "@Interface\AddOns\Grail\Grail.lua"]:9752: in function <Interface\AddOns\Grail\Grail.lua:9740>
> [string "=(tail call)"]: ?
> [string "@Interface\AddOns\Grail\Grail.lua"]:10040: in function `QuestsInMap'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:1432: in function `_ClassifyQuestsInMap'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:1885: in function `_ForcePanelMapArea'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:4417: in function `UpdateQuestCaches'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:1378: in function `f'
> [string "@Interface\AddOns\Grail\Grail.lua"]:8834: in function `_PostNotification'
> [string "@Interface\AddOns\Grail\Grail.lua"]:9024: in function `_ProcessDelayedNotifications'
> [string "@Interface\AddOns\Grail\Grail.lua"]:8823: in function <Interface\AddOns\Grail\Grail.lua:8823>
> 
> Locals: 

> Message: Interface\AddOns\Grail\Grail.lua:10092: attempt to index field 'rawLocations' (a nil value)
> Time: Mon Oct 19 11:18:49 2020
> Count: 1
> Stack: Interface\AddOns\Grail\Grail.lua:10092: attempt to index field 'rawLocations' (a nil value)
> [string "=[C]"]: ?
> [string "@Interface\AddOns\Grail\Grail.lua"]:10092: in function `_RawNPCLocations'
> [string "@Interface\AddOns\Grail\Grail.lua"]:8549: in function `NPCLocations'
> [string "@Interface\AddOns\Grail\Grail.lua"]:9752: in function <Interface\AddOns\Grail\Grail.lua:9740>
> [string "=(tail call)"]: ?
> [string "@Interface\AddOns\Grail\Grail.lua"]:10040: in function `QuestsInMap'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:1432: in function `_ClassifyQuestsInMap'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:1885: in function `_ForcePanelMapArea'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:4417: in function `UpdateQuestCaches'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:963: in function `?'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:2532: in function `_OnEvent'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:4433: in function <Interface\AddOns\Wholly\Wholly.lua:4433>
> 
> Locals: 

> Message: Interface\AddOns\Grail\Grail.lua:10092: attempt to index field 'rawLocations' (a nil value)
> Time: Mon Oct 19 11:18:47 2020
> Count: 1
> Stack: Interface\AddOns\Grail\Grail.lua:10092: attempt to index field 'rawLocations' (a nil value)
> [string "=[C]"]: ?
> [string "@Interface\AddOns\Grail\Grail.lua"]:10092: in function `_RawNPCLocations'
> [string "@Interface\AddOns\Grail\Grail.lua"]:8549: in function `NPCLocations'
> [string "@Interface\AddOns\Grail\Grail.lua"]:9752: in function <Interface\AddOns\Grail\Grail.lua:9740>
> [string "=(tail call)"]: ?
> [string "@Interface\AddOns\Grail\Grail.lua"]:10040: in function `QuestsInMap'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:1432: in function `_ClassifyQuestsInMap'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:3274: in function `_RecordTooltipNPCs'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:669: in function `?'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:2532: in function `_OnEvent'
> [string "@Interface\AddOns\Wholly\Wholly.lua"]:4433: in function <Interface\AddOns\Wholly\Wholly.lua:4433>
> 
> Locals: 

> Message: Interface\AddOns\Grail\Grail.lua:10092: attempt to index field 'rawLocations' (a nil value)
> Time: Mon Oct 19 11:18:44 2020
> Count: 1
> Stack: Interface\AddOns\Grail\Grail.lua:10092: attempt to index field 'rawLocations' (a nil value)
> [string "=[C]"]: ?
> [string "@Interface\AddOns\Grail\Grail.lua"]:10092: in function `_RawNPCLocations'
> [string "@Interface\AddOns\Grail\Grail.lua"]:8549: in function `NPCLocations'
> [string "@Interface\AddOns\Grail\Grail.lua"]:4494: in function `_UpdateWorldQuestSelfNPC'
> [string "@Interface\AddOns\Grail\Grail.lua"]:4525: in function `?'
> [string "@Interface\AddOns\Grail\Grail.lua"]:1636: in function `?'
> [string "@Interface\AddOns\Grail\Grail.lua"]:10992: in function `_Tooltip_OnEvent'
> [string "@Interface\AddOns\Grail\Grail.lua"]:11532: in function <Interface\AddOns\Grail\Grail.lua:11532>
> 
> Locals:

**Comment by smaitch** [comment]
Can you download the current version of Grail-112 from GitHub to see if it fixes the problem?

**Comment by ReglohPri** [comment]
I see only Grail-111.
Where is 112?

**Comment by smaitch** [comment]
It is the current code being developed.  There is no release tag for it yet.

**Comment by smaitch** [comment]
Grail 112 has been released.
