### ISSUE TITLE
Getting this bug in Garrison

### ISSUE THREAD

**Issue by DoctorShades24** [smaitch/Grail#240]
31x Grail\Grail-111.lua:8791: Usage: GetGarrisonInfo(garrisonType)
[string "=[C]"]: in function `GetGarrisonInfo'
[string "@Grail\Grail-111.lua"]:8791: in function `_PhaseMatches'
[string "@Grail\Grail-111.lua"]:6426: in function `f'
[string "@Grail\Grail-111.lua"]:3728: in function `_AllEvaluateTrueS'
[string "@Grail\Grail-111.lua"]:3828: in function <Grail\Grail.lua:3809>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Grail\Grail-111.lua"]:8111: in function `MeetsPrerequisites'
[string "@Grail\Grail-111.lua"]:10784: in function `StatusCode'
[string "@Grail\Grail-111.lua"]:6603: in function `f'
[string "@Grail\Grail-111.lua"]:3728: in function `_AllEvaluateTrueS'
[string "@Grail\Grail-111.lua"]:3828: in function <Grail\Grail.lua:3809>
...
[string "@Grail\Grail-111.lua"]:3828: in function <Grail\Grail.lua:3809>
[string "=(tail call)"]: ?
[string "@Grail\Grail-111.lua"]:3745: in function `AncestorStatusCode'
[string "@Grail\Grail-111.lua"]:10786: in function `StatusCode'
[string "@Grail\Grail-111.lua"]:4283: in function `ClassificationOfQuestCode'
[string "@Wholly\Wholly-080.lua"]:1434: in function `_ClassifyQuestsInMap'
[string "@Wholly\Wholly-080.lua"]:3274: in function `_RecordTooltipNPCs'
[string "@Wholly\Wholly-080.lua"]:669: in function `?'
[string "@Wholly\Wholly-080.lua"]:2532: in function `_OnEvent'
[string "@Wholly\Wholly-080.lua"]:4433: in function <Wholly\Wholly.lua:4433>

Locals:
(*temporary) = nil

**Comment by smaitch** [comment]
This should be fixed in the current code on GitHub for Grail (which when released will be version 112).

**Comment by DoctorShades24** [comment]
Thanks!

Is this the same situation?

I couldn't copy the text because the error keeps occurring over and over constantly.  Zipped the file due to size requirements.


[Screen Shot 2020-10-20 at 11.28.01 AM.zip](https://github.com/smaitch/Grail/files/5410122/Screen.Shot.2020-10-20.at.11.28.01.AM.zip)

**Comment by smaitch** [comment]
Yes, it is the same issue.
