### ISSUE TITLE
Lua errors from Grail + Wholly (retail EnUs)

### ISSUE THREAD

**Issue by Zathriam** [smaitch/Grail#241]
I'm not familiar with this github thing, nor bugreporting in general, so I apologize if these are issues that have allready come up.

The world map displays no quest pins, and quite often it gets messed up, showing the old map when switching to look at a different zone-map, or better yet, the old map and the new map strangely combined. :)

Lua error dump as follows from bugsack (which I'm also not familiar with):

1x Grail\Grail-111.lua:8791: Usage: GetGarrisonInfo(garrisonType)
[string "=[C]"]: in function `GetGarrisonInfo'
[string "@Grail\Grail-111.lua"]:8791: in function `_PhaseMatches'
[string "@Grail\Grail-111.lua"]:6426: in function `f'
[string "@Grail\Grail-111.lua"]:3728: in function `_AllEvaluateTrueS'
[string "@Grail\Grail-111.lua"]:3828: in function <Grail\Grail.lua:3809>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Grail\Grail-111.lua"]:8111: in function `MeetsPrerequisites'
[string "@Grail\Grail-111.lua"]:10784: in function `StatusCode'
[string "@Grail\Grail-111.lua"]:3997: in function `CanAcceptQuest'
[string "@Grail\Grail-111.lua"]:6391: in function `f'
[string "@Grail\Grail-111.lua"]:3728: in function `_AllEvaluateTrueS'
...
[string "@Wholly\Wholly-080.lua"]:1434: in function `_ClassifyQuestsInMap'
[string "@Wholly\Wholly-080.lua"]:798: in function `RefreshAllData'
[string "@Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:559: in function <...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:557>
[string "=[C]"]: ?
[string "=[C]"]: in function `OnMapChanged'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:59: in function `SetMapID'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:765: in function `NavigateToCursor'
[string "@Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:110: in function <...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:102>

Locals:
(*temporary) = nil

1x FrameXML\QuestMapFrame.lua:1640: Usage: GetAchievementNumCriteria(achievementID [,countHidden])
[string "=[C]"]: in function `GetAchievementNumCriteria'
[string "@FrameXML\QuestMapFrame.lua"]:1640: in function <FrameXML\QuestMapFrame.lua:1620>

Locals:
(*temporary) = nil

73x Grail\Grail-111.lua:7142: Usage: GetBuildings(garrisonType)
[string "=[C]"]: in function `GetBuildings'
[string "@Grail\Grail-111.lua"]:7142: in function `HasGarrisonBuilding'
[string "@Grail\Grail-111.lua"]:7172: in function `HasGarrisonBuildingInPlot'
[string "@Grail\Grail-111.lua"]:6432: in function `f'
[string "@Grail\Grail-111.lua"]:3694: in function `_AllEvaluateTrueF'
[string "@Grail\Grail-111.lua"]:3797: in function `_AnyEvaluateTrueF'
[string "@Grail\Grail-111.lua"]:9773: in function <Grail\Grail.lua:9740>
[string "=(tail call)"]: ?
[string "@Grail\Grail-111.lua"]:10040: in function `QuestsInMap'
[string "@Wholly\Wholly-080.lua"]:1432: in function `_ClassifyQuestsInMap'
[string "@Wholly\Wholly-080.lua"]:3274: in function `_RecordTooltipNPCs'
[string "@Wholly\Wholly-080.lua"]:669: in function `?'
[string "@Wholly\Wholly-080.lua"]:2532: in function `_OnEvent'
[string "@Wholly\Wholly-080.lua"]:4433: in function <Wholly\Wholly.lua:4433>

Locals:
(*temporary) = nil
(*temporary) = <table> {
}

26x ...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:185: attempt to index field 'ticker' (a nil value)
[string "@Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua"]:185: in function `OnHide'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:93: in function `OnHide'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:269: in function <...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:268>
[string "=[C]"]: in function `Hide'
[string "@FrameXML\UIParent.lua"]:2877: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2957: in function `HideUIPanel'
[string "@FrameXML\UIParent.lua"]:2610: in function <FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3477: in function <FrameXML\UIParent.lua:3460>
[string "=[C]"]: in function `HideUIPanel'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:101: in function `SetDisplayState'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:435: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
self = <table> {
 OnClearFocusedQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:79
 EvaluateCheckBounties = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:63
 poiQuantizer = <table> {
 }
 OnMapInsetMouseLeave = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:46
 AddWorldQuest = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:308
 GetBountyQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:149
 SetMatchWorldMapFilters = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:3
 OnCanvasScaleChanged = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:50
 registeredEvents = <table> {
 }
 PingQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:153
 owningMap = WorldMapFrame {
 }
 OnSetFocusedQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:75
 activePins = <table> {
 }
 DoesWorldQuestInfoPassFilters = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:191
 ShouldShowQuest = <function> defined @Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:7
 GetMap = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:70
 OnCanvasSizeChanged = <function> defined @Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:35
 markActiveQuests = true
 checkBounties = true
 usesSpellEffect = true
 matchWorldMapFilters = false
 IsMarkingActiveQuests = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:98
 OnRemoved = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:120
 OnAdded = <function> defined @Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:15
 OnMapChanged = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:74
 OnSuperTrackingChanged = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:255
 IsUsingSpellEffect = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:23
 ClearFocusedQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:134
 SignalEvent = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:97
 GetPinTemplate = <function> defined @Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:3
 ShouldHighlightInfo = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:274
 ShouldOverrideShowQuest = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:196
 IsQuestSuppressed = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:381
 spellEffectPin = <unnamed> {
 }
 suppressedQuests = <table> {
 }
 OnMapInsetSizeChanged = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:38
 IsCheckingBounties = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:59
 OnShow = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:177
 SetCheckBounties = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:50
 SetUsesSpellEffect = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:15
 SetBountyQuestID = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:139
 SuppressQuest = <function> defined @Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:374
 OnCanvasPanChanged = <function> defined @Interfa

**Comment by smaitch** [comment]
The Grail issues here should be fixed with Grail 112 which is now released.
