### ISSUE TITLE
Compatibility with quest-helpers

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#244]
Various other addons provide quality of life functions like auto accept, auto turn in of quests similiar to the auto-loot feature of the blizzard interface. In the past this broke grails recording and debug features including but not limited to getting the npc id and trouble with the quest id not matching expected values.
Is there something we can do to get around this kind of trouble when people use addons like Zygor Guides or Azeroth Auto Pilot?

**Comment by smaitch** [comment]
Grail was recently changed to handle the NPC acquisition in a slightly different manner that should work better than it did before.  Grail should be using the event system to handle this, so I would imagine it should work in general.  Are you seeing problems when using other addons where Grail is not getting the information we use?

**Comment by yoshimo** [comment]
NPCs seem to be better now.
Leaves us with #45
