### ISSUE TITLE
Quests showing as level "255<"

### ISSUE THREAD

**Issue by urodoc** [smaitch/Grail#247]
Wow Classic current. Using Wholly, many but not all quests show as level "255<". I've tried submitting an issue under Wholly also, but I don't know if it's a problem with Wholly or Grail. No change if I disable all other addons. Suggestion?

**Comment by smaitch** [comment]
Where are you seeing this?  Can you send a screenshot?  I have looked at lots of quests from various different characters in Classic and all of them seem to have reasonable levels and required levels.

**Comment by lordgromet** [comment]
![image](https://user-images.githubusercontent.com/49919517/105565434-9b6ae800-5cdb-11eb-98e0-af9573ddcf31.png)
It seems that after the quest updates (for example you pick it up or complete it) the level bugs out and displays 255<.  The only fix I have found is to delete the saved variables for Grail.  It will then appear correct until the quest is updated again.

**Comment by Nerillida** [comment]
smaitch

You fixed this in latest versions, can be closed.
