### ISSUE TITLE
'Rememberance' Misspelled

### ISSUE THREAD

**Issue by Hendo72** [smaitch/Grail#248]
G[31865]='FLAG - Offering of Rememberance'
My VSC checker flagged this as misspelled. I confirmed in game.
![image](https://user-images.githubusercontent.com/39675478/101288369-31968d80-37c4-11eb-93e7-7199d440a53a.png)

**Comment by smaitch** [comment]
The flag quest's name was pulled from the Blizzard quest names.  I would guess that Blizzard is misspelling the name of the quest.  I just checked wowhead.com and they spell the quest name the same way Grail does, so I believe this is what the system actually is reporting, and thus Blizzard will have to fix its values.
