### ISSUE TITLE
Data 03.01.2021

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#256]
Way to 60, Revendreth is unfinished.
One quest in the campaign is broken and marked as "unavailable" and causes follow up errors. 
[Grail_retail_03.01.2021.zip](https://github.com/smaitch/Grail/files/5761529/Grail_retail_03.01.2021.zip)

**Comment by yoshimo** [comment]
Looks like 57131 might be the offender as it is a normal quest but in wholly marked as "not available (pending)"

**Comment by smaitch** [comment]
I think I noticed that a bit ago, and removed the offending E code.  I just pushed my latest changes up but have not checked out your zip file yet.

**Comment by smaitch** [comment]
File processed for Grail 114 release.
