### ISSUE TITLE
LUA error when starting a new character and taking the first Exiles Reach quest

### ISSUE THREAD

**Issue by JacobraPDX** [smaitch/Grail#257]
I get the following LUA error when taking the first quest for Exiles reach beginner zone:

Message: Interface\AddOns\Grail\Grail.lua:6947: attempt to index field '?' (a nil value)
Time: Thu Jan  7 22:14:51 2021
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:6947: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\Grail\Grail.lua"]:6947: in function `GetPlayerMapPosition'
[string "@Interface\AddOns\Grail\Grail.lua"]:11031: in function `Coordinates'
[string "@Interface\AddOns\Grail\Grail.lua"]:1881: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:11074: in function `_Tooltip_OnEvent'
[string "@Interface\AddOns\Grail\Grail.lua"]:11622: in function <Interface\AddOns\Grail\Grail.lua:11622>

Locals: unitName = "player"
MapID = 1727
R = <table> {
}
P = <table> {
 DivideBy = <function> defined @Interface\SharedXML\Vector2D.lua:90
 GetLength = <function> defined @Interface\SharedXML\Vector2D.lua:118
 Normalize = <function> defined @Interface\SharedXML\Vector2D.lua:122
 Dot = <function> defined @Interface\SharedXML\Vector2D.lua:106
 GetLengthSquared = <function> defined @Interface\SharedXML\Vector2D.lua:114
 GetXY = <function> defined @Interface\SharedXML\Vector2D.lua:77
 OnLoad = <function> defined @Interface\SharedXML\Vector2D.lua:68
 IsZero = <function> defined @Interface\SharedXML\Vector2D.lua:110
 RotateDirection = <function> defined @Interface\SharedXML\Vector2D.lua:126
 x = 0
 y = 0
 IsEqualTo = <function> defined @Interface\SharedXML\Vector2D.lua:72
 Clone = <function> defined @Interface\SharedXML\Vector2D.lua:130
 Cross = <function> defined @Interface\SharedXML\Vector2D.lua:102
 Subtract = <function> defined @Interface\SharedXML\Vector2D.lua:98
 SetXY = <function> defined @Interface\SharedXML\Vector2D.lua:81
 ScaleBy = <function> defined @Interface\SharedXML\Vector2D.lua:86
 Add = <function> defined @Interface\SharedXML\Vector2D.lua:94
}
_ = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
 DivideBy = <function> defined @Interface\SharedXML\Vector2D.lua:90
 GetLength = <function> defined @Interface\SharedXML\Vector2D.lua:118
 Normalize = <function> defined @Interface\SharedXML\Vector2D.lua:122
 Dot = <function> defined @Interface\SharedXML\Vector2D.lua:106
 GetLengthSquared = <function> defined @Interface\SharedXML\Vector2D.lua:114
 GetXY = <function> defined @Interface\SharedXML\Vector2D.lua:77
 OnLoad = <function> defined @Interface\SharedXML\Vector2D.lua:68
 IsZero = <function> defined @Interface\SharedXML\Vector2D.lua:110
 RotateDirection = <function> defined @Interface\SharedXML\Vector2D.lua:126
 x = 1
 y = 1
 IsEqualTo = <function> defined @Interface\SharedXML\Vector2D.lua:72
 Clone = <function> defined @Interface\SharedXML\Vector2D.lua:130
 Cross = <function> defined @Interface\SharedXML\Vector2D.lua:102
 Subtract = <function> defined @Interface\SharedXML\Vector2D.lua:98
 SetXY = <function> defined @Interface\SharedXML\Vector2D.lua:81
 ScaleBy = <function> defined @Interface\SharedXML\Vector2D.lua:86
 Add = <function> defined @Interface\SharedXML\Vector2D.lua:94
}
(*temporary) = 1
(*temporary) = 1
(*temporary) = "attempt to index field '?' (a nil value)"

**Comment by yoshimo** [comment]
Which version of grail&wholly are you using?

**Comment by smaitch** [comment]
This should be fixed by using the latest version of Grail from GitHub (and will be fixed in Grail 114 when it is released generally).

**Comment by JacobraPDX** [comment]
I am using grail version 113.  I think it is because there are no coordinates while on the ship.  Good to know it will be fixed in the next version. I just like to report problems when I see them so they can be fixed, or someone can tell me what I am doing wrong. :) I really appreciate how response you have been when I have filed issues.  You are an awesome addon developer!

**Comment by smaitch** [comment]
Grail 114 was just released to the public so I will close this now.
