### ISSUE TITLE
No Reputation mapping

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#258]
`no reputation mapping for  9A0
no reputation mapping for  9A0
no reputation mapping for  99E
no reputation mapping for  99E
no reputation mapping for  9A0
no reputation mapping for  99E
no reputation mapping for  99E
no reputation mapping for  99E
no reputation mapping for  9A0
no reputation mapping for  9A0
no reputation mapping for  99E
no reputation mapping for  99E
no reputation mapping for  99E
no reputation mapping for  9A0
no reputation mapping for  99E
no reputation mapping for  99E
no reputation mapping for  99E`

**Comment by smaitch** [comment]
Grail 114 (and what is currently in GitHub) has changes for this.
