### ISSUE TITLE
Covenants & Renown events/API

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#259]
Since quests on level 60 depend on the chosen covenant and the renown standing with them we should make use of

https://wow.gamepedia.com/Category:API_namespaces/C_CovenantSanctumUI

COVENANT_CHOSEN (event)
returns the ID of the covenant

local covenantID = C_Covenants.GetCovenantIDs()
local covenantID = C_Covenants.GetActiveCovenantID()

local level = C_CovenantSanctumUI.GetRenownLevel()
local levels = C_CovenantSanctumUI.GetRenownLevels(covenantID)
local rewards = C_CovenantSanctumUI.GetRenownRewardsForLevel(covenantID, renownLevel)

COVENANT_RENOWN_INTERACTION_ENDED
COVENANT_RENOWN_INTERACTION_STARTED

COVENANT_SANCTUM_RENOWN_LEVEL_CHANGED
COVENANT_SANCTUM_RENOWN_LEVEL_CHANGED: newRenownLevel, oldRenownLevel

So that the log includes hints about the changes so we can track quests more easily

**Comment by smaitch** [comment]
Grail 114 (and GitHub) has registered for some events to help process covenant changes and renown level changes to have the quest statuses updated.

**Comment by yoshimo** [comment]
I think we should 
- print the current covenant & renown level to log on login
- log and print the covenant change to chat & log it
- log and print the renown level change to chat & log it

in addition to just invalidating quests when we observe changes.

**Comment by smaitch** [comment]
The latest Grail in GitHub (and 114) has logging as suggested.
