### ISSUE TITLE
Void Elf and Grail

### ISSUE THREAD

**Issue by LordDeimos666** [smaitch/Grail#26]
Dunno if it's related to void elf new allied subrace.
But I'm getting this error on login:

> 8x Grail\Grail-092.lua:6651: bad argument #2 to 'bitband' (number expected, got nil)
[C]: ?
Grail\Grail-092.lua:6651: in function <Grail\Grail.lua:6600>
(tail call): ?
Grail\Grail-092.lua:8862: in function `StatusCode'
Grail\Grail-092.lua:3506: in function `ClassificationOfQuestCode'
Wholly\Wholly-065.lua:1321: in function `_ClassifyQuestsInMap'
Wholly\Wholly-065.lua:1767: in function `_ForcePanelMapArea'
Wholly\Wholly-065.lua:4074: in function `UpdateQuestCaches'
Wholly\Wholly-065.lua:853: in function `?'
Wholly\Wholly-065.lua:2342: in function `_OnEvent'
Wholly\Wholly-065.lua:2525: in function <Wholly\Wholly.lua:2525>
>Locals:
(*temporary) = 536870911
(*temporary) = nil
(*temporary) = "number expected, got nil"

**Comment by AikoTM** [comment]
Got this with my Lightforged Draenei aswell.

**Comment by LordDeimos666** [comment]
Ye seems pretty related to the new allied race. For now Disabling the addon on those toons.

**Comment by yoshimo** [comment]
What does /dump UnitRace('player') give you for those new races?

**Comment by smaitch** [comment]
I have a new Grail that can support the Alliance Allied races, however I need some help with the Horde ones.  Can someone upload the results from the slash command:
 
/dump UnitRace("player")
 
when playing each of the Horde Allied races.  I can then update Grail and get a release out that will not have this issue.

**Comment by Ayvalen** [comment]
Here you go, smaitch!

[02:11:41] Dump: value=UnitRace("player")
[02:11:41] [1]="Highmountain Tauren",
[02:11:41] [2]="HighmountainTauren

[02:12:57] Dump: value=UnitRace("player")
[02:12:57] [1]="Nightborne",
[02:12:57] [2]="Nightborne

**Comment by Cerro67** [comment]
Hi, where and how can you integrate this in the addon so that it is working as a newcomer ... because for new races Wolly is not thanks for the tips

**Comment by yoshimo** [comment]
@Cerro67 just wait for the next update by @smaitch

**Comment by smaitch** [comment]
Grail and Wholly have been updated to allow for Allied races now.
