### ISSUE TITLE
Modified addon warning

### ISSUE THREAD

**Issue by Hollthulhu** [smaitch/Grail#260]
Hi, I am a Curseforge user and I noticed that my Grail has a warning beside it that states my files may be corrupt and that is "modified". I do know some few addons have this happen normally, but I wasn't sure if this was the case for Grail. I did not see anything on the Curseforge home page for the addon that stated how to handle this issue, but it may be nice to put a small blurb there in case anyone else has this simple question in the future. If I do need to fix it, are there any extra steps I need to take other than using the uninstall/install options in Curseforge's app?

Thanks so much!

**Comment by smaitch** [comment]
The only way I imagine this could be happening is if the addon you have on disk differs from what CurseForge thinks there should be there.  This could happen if you were to download a version of the addon from GitHub for example.  Otherwise, I would not have any idea why this is happening.

**Comment by smaitch** [comment]
One assume reinstallation of it has worked.
