### ISSUE TITLE
Classic - Zando'zan PRE?

### ISSUE THREAD

**Issue by Hendo72** [smaitch/Grail#275]
Wowhead seems to be mistaken about:
![image](https://user-images.githubusercontent.com/39675478/113498538-ce033f00-94db-11eb-94cf-452dfa8a3837.png)
I can accept the quest without having gone near the other 2 quests.

**Comment by Ludovicus-Maior** [comment]
```
Grail-Quests-_classic_/Grail-Quests-_classic_.lua:G[2379]='L1052927 CR A:3401 T:3402 P:2378,2380 E31727
```
I suspect 2378 and 2380 are lead in quests and not actual prerequisites.

**Comment by Nerillida** [comment]
2378 and 2379 are mutually exclusive breadcrumbs to 2379. Obviously they are rogue specific. I did not determine if they were racially different.

**Comment by smaitch** [comment]
Grail has been updated for next release to make them prerequisites.
