### ISSUE TITLE
Wholly & Grail TBC LUA Issues

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#278]
Okay, so I managed to get an old version of swatter working, so here's the issues that it procs up for Grail on the current TBC Prepatch:

Date: 2021-05-28 10:19:26
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Grail\Grail.lua line 1382:
   attempt to call global 'GetFriendshipReputation' (a nil value)
Debug:
   [string "=[C]"]: GetFriendshipReputation()
   [string "@Grail\Grail.lua"]:1382: ?()
   [string "@Grail\Grail.lua"]:11074: _Tooltip_OnEvent()
   [string "@Grail\Grail.lua"]:11622:
      Grail\Grail.lua:11622
Locals:

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  WowheadLooter, v20501
  AccountantClassic, vv2.12.08.20501.00
  Armory, vv1.1.1
  ATTClassic, v0.5.7
  ButtonForge, v1.0.5-classic-TBC
  DBMCore, v2.5.4
  DBMStatusBarTimers, v
  ExtendedMapZoneInfoForClassic, v1.5
  FleecingTip, v113.1770(200720)
  GatherMate2, v1.46.0-classic
  Grail, v113
  GrailQuestsretailenUS, v31478
  HandyNotes, vv1.6.3
  LetMeFly, v1.0
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SlideBar, v1.13.6668 (SwimmingSeadragon)
  Spy, v1.1.2
  TradeSkillMaster, vv4.10.39
  TradeSkillMasterAppHelper, vv4.0.14
  Wholly, v079
  WIM, v3.9.1
  BlizRuntimeLib_enUS v2.5.1.20501 <none>
  (ck=297)
  
  =================================================================================
  
  And here's the Wholly issue for reference:
  
  Date: 2021-05-28 10:19:26
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Wholly\Wholly.lua line 3852:
   attempt to call method 'SetBackdrop' (a nil value)
Debug:
   [string "=[C]"]: SetBackdrop()
   [string "@Wholly\Wholly.lua"]:3852: _SetupSearchFrame()
   [string "@Wholly\Wholly.lua"]:686: ?()
   [string "@Wholly\Wholly.lua"]:2526: _OnEvent()
   [string "@Wholly\Wholly.lua"]:4427:
      Wholly\Wholly.lua:4427
Locals:

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  WowheadLooter, v20501
  AccountantClassic, vv2.12.08.20501.00
  Armory, vv1.1.1
  ATTClassic, v0.5.7
  ButtonForge, v1.0.5-classic-TBC
  DBMCore, v2.5.4
  DBMStatusBarTimers, v
  ExtendedMapZoneInfoForClassic, v1.5
  FleecingTip, v113.1770(200720)
  GatherMate2, v1.46.0-classic
  Grail, v113
  GrailQuestsretailenUS, v31478
  HandyNotes, vv1.6.3
  LetMeFly, v1.0
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SlideBar, v1.13.6668 (SwimmingSeadragon)
  Spy, v1.1.2
  TradeSkillMaster, vv4.10.39
  TradeSkillMasterAppHelper, vv4.0.14
  Wholly, v079
  WIM, v3.9.1
  BlizRuntimeLib_enUS v2.5.1.20501 <none>
  (ck=297)

**Comment by yoshimo** [comment]
check out the discussion in #277

**Comment by Wyr3d** [comment]
Yeah, I'm not sure what's going on in that discussion. If that a fix, or still being worked on?

**Comment by yoshimo** [comment]
the changes by @smaitch there should fix it for now.
Can't test it at the moment

**Comment by smaitch** [comment]
I have pushed some more changes today.  If you download the latest Wholly and Grail from GitHub I believe they should work.  I have tested on the Classic PTR today and it seems to work.  Please try downloading them to see if they work for you.

**Comment by Wyr3d** [comment]
I have downloaded, and installed the latest versions. I only poked my head in, and played around with the settings a little,, but it seems to be working fine. Completion date data isn't available for past quests, but that's prolly more down the Blizzard than the add-on. Nice work ^^

**Comment by smaitch** [comment]
The latest versions of Wholly and Grail are now out officially.
