### ISSUE TITLE
Wow Classic/TBC problems

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#281]
I downloaded those files that you mentioned in 

https://github.com/smaitch/Grail/issues/278#issue-905030970

It seems to work well, BUT, some low level quest are displayed with a level of 255

![Screen Shot 2021-05-31 at 16 38 30](https://user-images.githubusercontent.com/55858788/120218019-110a3600-c231-11eb-85e8-ed40def1320c.png)

Not sure if this is a Wholly or Grail problem.

Thanks

**Comment by smaitch** [comment]
Normally this would be a Grail problem.  I have not done any work with the new Grail in Classic to get the proper levels based on that code.  However, I will see what I can do.

**Comment by Nerillida** [comment]
Thanks, interesting that the completed quests ae 255, others not altered.
mybe a clue.

**Comment by smaitch** [comment]
I just checked on the Classic PTR and the quests are showing up as expected (though I have not checked completed quests).

**Comment by smaitch** [comment]
I just checked with the starting quests for a level 58 on Classic PTR and completed quests are showing the levels as expected.

**Comment by smaitch** [comment]
I just checked with a starter character on Classic PTR in Teldrassil and it seems to be performing as expected.
<img width="577" alt="Screen Shot 2021-05-31 at 13 46 21" src="https://user-images.githubusercontent.com/18412543/120227350-fa56e580-c216-11eb-9716-a3a4103cfd3f.png">

**Comment by Nerillida** [comment]
Sorry, no change, deleted Saved variables

Here's another example. Seems to have 255 for the level, required level  OK

Only for completed  quests, but not all of them.

 would look but  haven idea where to start.
Another sample.

![Screen Shot 2021-05-31 at 19 20 30](https://user-images.githubusercontent.com/55858788/120230195-ba0f5b80-c246-11eb-871b-97d8ef768f43.png)

**Comment by smaitch** [comment]
I logged into live Classic Burning Crusade seems to be ok as well.

Are you saying some of the quests that are completed show their proper level, and some show level 255?

**Comment by Nerillida** [comment]
Yes

![Screen Shot 2021-05-31 at 19 41 42](https://user-images.githubusercontent.com/55858788/120231063-7f0e2780-c248-11eb-964e-a6361568521a.png)
![Screen Shot 2021-05-31 at 19 41 56](https://user-images.githubusercontent.com/55858788/120231069-82a1ae80-c248-11eb-9dde-b1fee8b23765.png)
![Screen Shot 2021-05-31 at 19 42 09](https://user-images.githubusercontent.com/55858788/120231107-951be800-c248-11eb-9ad8-9a383c649ef4.png)
![Screen Shot 2021-05-31 at 19 42 22](https://user-images.githubusercontent.com/55858788/120231111-99e09c00-c248-11eb-9627-b8c96f6512eb.png)
![Screen Shot 2021-05-31 at 19 42 22](https://user-images.githubusercontent.com/55858788/120231119-9d742300-c248-11eb-82d4-52b36331fd5a.png)
![Screen Shot 2021-05-31 at 19 42 37](https://user-images.githubusercontent.com/55858788/120231123-a06f1380-c248-11eb-8bfc-7212de24150b.png)
![Screen Shot 2021-05-31 at 19 42 50](https://user-images.githubusercontent.com/55858788/120231138-ab29a880-c248-11eb-818e-3bff8c9af9e5.png)
![Screen Shot 2021-05-31 at 19 43 05](https://user-images.githubusercontent.com/55858788/120231146-afee5c80-c248-11eb-8f36-e6f9410878f2.png)

**Comment by smaitch** [comment]
Can you attach your Grail.lua saved variables file for someone that shows this UI?  For example, quest 344 shown above in the latest Grail has the level code L5144 which translates as levels 20 and 24 as expected.

**Comment by Nerillida** [comment]
Here's the saved variables for the one I screen shotted above, bear in mind that it's "new".

[Grail.lua.zip](https://github.com/smaitch/Grail/files/6571864/Grail.lua.zip)

**Comment by smaitch** [comment]
Actually that is for the character.  Can you send me the one for the account, and not a specific character?  What I am looking for specifically should be in entries in the file called "learned", which are not in the file associated with a specific character.

**Comment by Nerillida** [comment]
Here, different accounts are played, so it may reflect this

[Grail.lua.zip](https://github.com/smaitch/Grail/files/6571895/Grail.lua.zip)

**Comment by smaitch** [comment]
I think if you exit WoW, remove that file from your system, then restart WoW things should appear properly.  The issue is you have a recording using the old level format that has been changed.  That old format when interpreted using the new system makes the 255 level.  Basically you have a line in the file that marks quest 344 with level code L6399 instead of the one Grail has of L5144.  Your file will override Grail's data because your file is what you have learned. However, you learned some things in an older version of Grail.  There is code in Grail that should have handled that properly, but now I need to see what is happening as it seems not to be in your case.

**Comment by smaitch** [comment]
I see the problem.  I did not implement the old style code....it still is a TODO in the Grail file.

**Comment by Nerillida** [comment]
Ahh, maybe, there have been too many years played. I will try it.

Surely easier to tell people to delete their old file.

**Comment by smaitch** [comment]
Yeah, that is usually easier.  But I prefer to try to do the work so people can just use the tool without worry.  I want to make things simple from that point of view.

**Comment by Nerillida** [comment]
Very creditable.

Yes, it's fine now. Thanks for your time.

While I have your attention - would it be possible to add the outland maps to Wholly/Grail and a Wholly selector?

I can work on the data files myself.

Grateful for your time.  Questie is fine but too different for me. And they don't handle things as well as you.

**Comment by smaitch** [comment]
I just pushed a change that should allow the Outland continent option, etc.  However, we do not have any quests in any of the zones at this time.  Any work you do for them will be appreciated.  Thanks.

**Comment by Nerillida** [comment]
Thanks very much. again.

**Comment by smaitch** [comment]
I pushed a change that should let your old saved variables file to be processed and not turn quests into level 255 quests.

**Comment by Nerillida** [comment]
Thanks

Trying to get Outland Belf/Draenei areas to show in Wholly.

**Comment by smaitch** [comment]
I just pushed a change to support Draenei and Blood Elf.  However, the zones (the two Isles, Gohostlands, etc.) were already there.

**Comment by smaitch** [comment]
To list the zones in the Wholly panel you probably need to use the Wholly preferences to show empty zones (as there are no quests in Grail in any of those zones currently).

**Comment by Nerillida** [comment]
Thanks, I'll stop bothering you for a while.  :)

**Comment by Nerillida** [comment]
Fixed. Thanks.
