### ISSUE TITLE
BCC-Data

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#283]
Get the ball rolling with Draenei and Bloodelf data.

**Comment by yoshimo** [comment]
[Grai_classicbeta_12_06_2021.zip](https://github.com/smaitch/Grail/files/6641800/Grai_classicbeta_12_06_2021.zip)

**Comment by smaitch** [comment]
Changes from this file are now pushed in dd6e675c326b5088d32d513b129c6704440d209a to the latest Grail on GitHub.
