### ISSUE TITLE
gril.lua file

### ISSUE THREAD

**Issue by hertzlatebitshort** [smaitch/Grail#284]
[Grail.lua.gz](https://github.com/smaitch/Grail/files/6643054/Grail.lua.gz)

**Comment by smaitch** [comment]
Processed and committed in https://github.com/smaitch/Grail/commit/347905c5ad5eda3f7f073a183c5f6e8e7a9bc62b and https://github.com/smaitch/Grail/commit/dea357c30dbeea08bc59a808f64d4f7b9b2c9eb5
