### ISSUE TITLE
TBC classic E and Z codes

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#285]
Hello,

I have some data regarding TBC. There were changes that need to be marked as from the beginning of pre-patch, only during pre-patch, at the end of prepunch onwards.

I can't work out which E and Z codes to use, I do not have access to a list of when they occurred. Grateful for help.

**Comment by smaitch** [comment]
If you know they are gone already, then the current build can be used for the Z code.  The system is designed with the ability to have good control of when something is introduced or expired, but it need not be too accurate.  Basically when there is a PTR out there the same data can be used for both PTR and release and should not affect a system where the data should not be present.  So, if something is in a PTR and not available in release just mark the E with one of the release values in the PTR that is not in the release.

**Comment by Nerillida** [comment]
Thanks
