### ISSUE TITLE
Curseforge info wrong

### ISSUE THREAD

**Issue by MyTechnoHunter** [smaitch/Grail#287]
hello, the curseforge client insists that the latest version available for download is 113.. not 116

![image](https://user-images.githubusercontent.com/55214545/135748848-1c1bf8e8-669c-4d40-9451-73f4573d7eec.png)

**Comment by smaitch** [comment]
Curseforge seems not to be able to properly handle one addon that can support all three Blizzard products (retail, classic and bcc) at the same time.  The latest Grail (and Wholly) have been updated to only list on Curseforge retail as being supported, even though they support all three.  Things will be better when Curseforge properly supports addons with multiple client support.
