### ISSUE TITLE
Bug Log: Lua Warning

### ISSUE THREAD

**Issue by sabanim** [smaitch/Grail#288]
Message: Interface\AddOns\Grail\Grail.lua:884: hooksecurefunc(): SelectGossipOption is not a function
Time: Mon Nov  1 13:59:40 2021
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:884: hooksecurefunc(): SelectGossipOption is not a function
[string "=[C]"]: ?
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\Grail\Grail.lua"]:884: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:7501: in function `_Tooltip_OnEvent'
[string "@Interface\AddOns\Grail\Grail.lua"]:8122: in function <Interface\AddOns\Grail\Grail.lua:8122>

Locals: 

Latest Retail Version as of 11/01/2021

**Comment by yoshimo** [comment]
The lines don't match the current version, curse recently had an issue where old versions were pushed
Could you verify that you are on the most recent version and there is no update available to you?

**Comment by smaitch** [comment]
The latest version of Grail should now fix this issue.
