### ISSUE TITLE
LUA Error 9.1.5

### ISSUE THREAD

**Issue by Zallanon** [smaitch/Grail#289]
Message: Interface\AddOns\Grail\Grail-074PR2.lua:884: hooksecurefunc(): SelectGossipOption is not a function
Time: Thu Nov  4 10:01:37 2021
Count: 1
Stack: Interface\AddOns\Grail\Grail-074PR2.lua:884: hooksecurefunc(): SelectGossipOption is not a function
[string "@Interface\AddOns\Grail\Grail.lua"]:8122: in function <Interface\AddOns\Grail\Grail.lua:8122>

Locals: frame = <unnamed> {
 0 = <userdata>
}
event = "ADDON_LOADED"

**Comment by yoshimo** [comment]
The lines don't match the current version, curse recently had an issue where old versions were pushed
Could you verify that you are on the most recent version and there is no update available to you?

**Comment by Zallanon** [comment]
The version I have is Grail-116, tagged in curseforge as game version 9.1.0

**Comment by yoshimo** [comment]
Does it happen at a special occasion or right after login?

**Comment by Zallanon** [comment]
Yeah right on login

Dave Bilenduke
***@***.***
(403)971-6765

**Comment by smaitch** [comment]
Does upgrading to the newly released Grail 117/Wholly 085 fix the problem for you?

**Comment by Zallanon** [comment]
Yes I no longer get the error on either. Thanks 

Dave Bilenduke
***@***.***
(403)971-6765

**Comment by smaitch** [comment]
Cool.
