### ISSUE TITLE
outdated version in toc file for classic era

### ISSUE THREAD

**Issue by MyTechnoHunter** [smaitch/Grail#290]
version should be 11401, instead its still 11400

**Comment by smaitch** [comment]
Interestingly, I find that I did not update the version in the non-retail TOC files to 117 as it should be. However, yes, Blizzard has updated the release and in the next release Grail will be updated, though there is no plan for that for some time.

**Comment by CanadianJeff** [comment]
+1

**Comment by smaitch** [comment]
The current version on GitHub has the latest interface values.
