### ISSUE TITLE
Error Lua had Wholly and Dugi active as well.

### ISSUE THREAD

**Issue by nator316** [smaitch/Grail#291]
Message: Interface\AddOns\Grail\Grail.lua:10846: attempt to index field 'rawLocations' (a nil value)
Time: Fri Jan  7 12:51:59 2022
Count: 1
Stack: Interface\AddOns\Grail\Grail.lua:10846: attempt to index field 'rawLocations' (a nil value)
[string "@Interface\AddOns\Grail\Grail.lua"]:10846: in function `_RawNPCLocations'
[string "@Interface\AddOns\Grail\Grail.lua"]:9038: in function `NPCLocations'
[string "@Interface\AddOns\Grail\Grail.lua"]:4820: in function `_UpdateWorldQuestSelfNPC'
[string "@Interface\AddOns\Grail\Grail.lua"]:4862: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:1737: in function `?'
[string "@Interface\AddOns\Grail\Grail.lua"]:11773: in function `_Tooltip_OnEvent'
[string "@Interface\AddOns\Grail\Grail.lua"]:12334: in function <Interface\AddOns\Grail\Grail.lua:12334>

Locals: self = <table> {
 QuestBreadcrumbsFor = <function> defined @Interface\AddOns\Grail\Grail.lua:10166
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Interface\AddOns\Grail\Grail.lua:7723
 totalRawNPCLocations = 0
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Interface\AddOns\Grail\Grail.lua:10932
 bitMaskCompleted = 1
 tooltip = com_mithrandir_grailTooltip {
 }
 professionCategoryIdMapping = <table> {
 }
 QuestLocationsAccept = <function> defined @Interface\AddOns\Grail\Grail.lua:10490
 IsAvailable = <function> defined @Interface\AddOns\Grail\Grail.lua:7705
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Interface\AddOns\Grail\Grail.lua:7387
 bitMaskClassAll = 268443644
 bitMaskQuestUnused4 = 33554432
 _HandleEventLootClosed = <function> defined @Interface\AddOns\Grail\Grail.lua:7415
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:5681
 _LevelGainedQuestCheckObserve = <function> defined @Interface\AddOns\Grail\Grail.lua:10186
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 GetNPCInformation = <function> defined @Interface\AddOns\Grail\Grail.lua:7236
 NPC_TYPE_DROP = "DROP"
 _GetWeeklyDay = <function> defined @Interface\AddOns\Grail\Grail.lua:7127
 _MarkQuestType = <function> defined @Interface\AddOns\Grail\Grail.lua:6080
 receivedCalendarUpdateEventList = false
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Interface\AddOns\Grail\Grail.lua:10664
 _ProcessServerBackup = <function> defined @Interface\AddOns\Grail\Grail.lua:9767
 bitMaskQuestVariableLevel = 255
 MeetsRequirementGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:8742
 _EvaluateCodeAsPrerequisite = <function> defined @Interface\AddOns\Grail\Grail.lua:6615
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Interface\AddOns\Grail\Grail.lua:8827
 DoesNPCExist = <function> defined @Interface\AddOns\Grail\Grail.lua:6580
 npcNames = <table> {
 }
 diversionMapping = <table> {
 }
 IsCallingQuest = <function> defined @Interface\AddOns\Grail\Grail.lua:8087
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Interface\AddOns\Grail\Grail.lua:9113
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Interface\AddOns\Grail\Grail.lua:3458
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Interface\AddOns\Grail\Grail.lua:8291
 _HandleEventAchievementEarned = <function> defined @Interface\AddOns\Grail\Grail.lua:7382
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 8192
 _ReputationExceeds = <function> defined @Interface\AddOns\Grail\Grail.lua:11121
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 reputationFriendsMaw = <table> {
 }
 _ContainsAliasNPC = <function> defined @Interface\AddOns\Grail\Grail.lua:6313
 classToBitMapping = <table> {
 }
 FriendshipReputation

**Comment by smaitch** [comment]
I take it without Dugi installed, Grail works properly.  It looks from the backtrace that there might be an issue loading the Grail-NPCs addon.  If this does not load it should report a problem in the chat.  Does this happen?  If this is not happening for you, is there a chance that you can give me what I would need to reproduce the problem here?  I do not have Dugi.

**Comment by nator316** [comment]
Today I got a Dugi report ill attach the screenshot I took when I get home.

The Dugi problems are different and constant.

example I use any flight path and the Quest Log starts swinging from left
to right by 2 millimeters

**Comment by smaitch** [comment]
I take it this must not be an issue any longer as nothing further came from it.
