### ISSUE TITLE
Suggestion: remove / add option to remove Grail server query alert in chat on login

### ISSUE THREAD

**Issue by addonaddict** [smaitch/Grail#293]
Hello,

Love the addon
Is it possible to add option to remove chat announcement on every login?
Either as global option or set by default when installing addon
I find this info not really important which is why im trying to clean up the chat spams everytime i login / reload

Thank you!

Example:
![image](https://user-images.githubusercontent.com/73442541/159469972-378be83d-3bff-4308-afbc-c8f62a1b86af.png)

**Comment by smaitch** [comment]
You should be able to use the slash command "/grail silent" to toggle whether these startup messages appear.

**Comment by addonaddict** [comment]
Thank you it worked.
Do I need to remember this command for every character I make / whenever I reset addons?
It would be great to incorporate this as a checkbox somewhere in the addon for these occasions… if you want to of course.
Again, thank you!
