### ISSUE TITLE
Suggestion: remove or add option to remove quest ID in quest window

### ISSUE THREAD

**Issue by addonaddict** [smaitch/Grail#294]
Hello,

Is there any possibility to add option to remove quest ID's or make this default addon behavior when installed?
I dont really have use for quest ID's but I dont see any option to not show it

Same question for world map markers that I never have use for...

Example:
![image](https://user-images.githubusercontent.com/73442541/159470405-dce1339f-0da3-4224-9749-38b4432ac2dc.png)

Example 2:
![image](https://user-images.githubusercontent.com/73442541/159470801-8b3ad597-e498-4c87-b6e9-ff0323f870a2.png)

Thank you

**Comment by smaitch** [comment]
This is being handled in ticket https://github.com/smaitch/Wholly/issues/49
