### ISSUE TITLE
quest change.

### ISSUE THREAD

**Issue by DreamOfHero** [smaitch/Grail#299]
Hi,

I don't know how to do it on my own with github, so I write an issue.
Quest Id 25354 is an Horde Only Quest.
so Line 8339 of file Grail-Quests-_retail_.lua of must be G[25354]='FH L30 A:39432 T:39432'
instead of: G[25354]='L30 A:39432 T:39432'

Thanks Andrea

**Comment by smaitch** [comment]
This change has been made for the next release of Grail.
