### ISSUE TITLE
Emissary of War - Incorrect Holiday mapping

### ISSUE THREAD

**Issue by eTzmNcbkrng** [smaitch/Grail#30]
Weekend Event quest Emissary of War (44171) is incorrectly reporting that it is only available during the Burning Crusade Timewalking Event.  
This is incorrect as it is only available during the Legion Dungeon Event

![wowscrnshot_042118_214819](https://user-images.githubusercontent.com/26512802/39082870-33db4528-45ae-11e8-95ab-643823727106.jpg)

**Comment by smaitch** [comment]
Grail has been updated for the next release.
