### ISSUE TITLE
STILL Broken for Wrath - LUA issue below

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#305]
Date: 2022-09-08 21:58:35
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Grail\Grail.lua line 1463:
   attempt to call global 'GetFriendshipReputation' (a nil value)
Debug:
   [string "=[C]"]: GetFriendshipReputation()
   [string "@Grail\Grail.lua"]:1463: ?()
   [string "@Grail\Grail.lua"]:11769: _Tooltip_OnEvent()
   [string "@Grail\Grail.lua"]:12330:
      Grail\Grail.lua:12330
Locals:

**Comment by Wyr3d** [comment]
Also for ease of reference, here's the Wholly LUA Error too

Date: 2022-09-08 21:58:35
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\Wholly\Wholly.lua line 3798:
   hooksecurefunc(): QuestMapLogTitleButton_OnEnter is not a function
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: hooksecurefunc()
   [string "@Wholly\Wholly.lua"]:3798: _SetupBlizzardQuestLogSupport()
   [string "@Wholly\Wholly.lua"]:777: ?()
   [string "@Wholly\Wholly.lua"]:2613: _OnEvent()
   [string "@Wholly\Wholly.lua"]:4536:
      Wholly\Wholly.lua:4536
Locals:

**Comment by yoshimo** [comment]
It doesn't use the classic  APIs yet.
I'll  make a pull request to do so tomorrow

**Comment by Wyr3d** [comment]
Still broken, but a new LUA error shows up

Date: 2022-09-10 22:35:08
ID: 4
Error occured in: Global
Count: 1
Message: ..\AddOns\Wholly\Wholly.lua line 1974:
   attempt to index field 'mapToContinentMapping' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Wholly\Wholly.lua"]:1974: _ForcePanelMapArea()
   [string "@Wholly\Wholly.lua"]:2863: _ProcessInitialUpdate()
   [string "@Wholly\Wholly.lua"]:2626: OnShow()
   [string "@Wholly\Wholly.lua"]:4120:
      Wholly\Wholly.lua:4119
   [string "=[C]"]: Show()
   [string "@Wholly\Wholly.lua"]:4467: ToggleUI()
   [string "@Wholly\Wholly.lua"]:4290: SlashCommand()
   [string "@Wholly\Wholly.lua"]:2081: ?()
   [string "@..\FrameXML\ChatFrame.lua"]:4933: ChatEdit_ParseText()
   [string "@..\FrameXML\ChatFrame.lua"]:4596: ChatEdit_SendText()
   [string "@..\FrameXML\ChatFrame.lua"]:2977:
      ..\FrameXML\ChatFrame.lua:2970
   [string "=[C]"]: UseAction()
   [string "@..\FrameXML\SecureTemplates.lua"]:343: handler()
   [string "@..\FrameXML\SecureTemplates.lua"]:625: SecureActionButton_OnClick()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:

**Comment by Wyr3d** [comment]
The following errors occur when logging into the game:

The Line 1463 error still occurs for Grail:

AddOns\Grail\Grail.lua line 1463:
   attempt to call global 'GetFriendshipReputation' (a nil value)
   
The line 3798 error still occurs for Wholly:

\AddOns\Wholly\Wholly.lua line 3798:
hooksecurefunc(): QuestMapLogTitleButton_OnEnter is not a function

The following error occurs when hitting "Interface" button in Game Menu  - this happens the first time pressed:

Date: 2022-09-13 19:30:30
ID: 5
Error occured in: Global
Count: 6
Message: ..\AddOns\Wholly\Wholly.lua line 1749:
   attempt to get length of field '?' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Wholly\Wholly.lua"]:1749: ConfigFrame_OnShow()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [string "=[C]"]: Show()
   [string "@Interface_Wrath\FrameXML\UIParent.lua"]:2215: SetUIPanel()
   [string "@Interface_Wrath\FrameXML\UIParent.lua"]:2021: ShowUIPanel()
   [string "@Interface_Wrath\FrameXML\UIParent.lua"]:1928:
      Interface_Wrath\FrameXML\UIParent.lua:1924
   [string "=[C]"]: SetAttribute()
   [string "@Interface_Wrath\FrameXML\UIParent.lua"]:2719: ShowUIPanel()
   [string "@Interface_Wrath\FrameXML\UIParent.lua"]:2744: ShowOptionsPanel()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:


So including the error on 1974 in the above post, that's 4 errors total

**Comment by yoshimo** [comment]
Any other sub module needs a Wrath compatible toc to load without warnings but i just did the ground work to test if everything works first.

**Comment by Wyr3d** [comment]
Welp, previously it was just loading the frame, and no quests listed, so it's much better now XD

**Comment by smaitch** [comment]
Humorously I had started work on things and my change has the variable called:

		existsClassicWrathOfTheLichKing = (WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC),

I also was renaming the TOC files using Vanilla, TBC and Wrath.  Though I have not researched it too in depth nor played with them.

**Comment by smaitch** [comment]
I have pushed changes to hopefully provide basic support for the three environments: Retail, Classic, and Classic WotLK.  I do not know if it is possible to have a Classic TBC environment any more.  I assume a lot of data for WotLK is going to have to be added as I just copied the Classic to WotLK without making additions.

**Comment by yoshimo** [comment]
>I do not know if it is possible to have a Classic TBC environment any more. I assume a lot of data for WotLK is going to have to be added as I just copied the Classic to WotLK without making additions.

For the time being Blizzard said there will be no TBC realm, but maybe we will get a season of mastery edition later on.
