### ISSUE TITLE
Do you know if Zygor benefits from this at all in terms of its decision making processing? WoW Retail enUS

### ISSUE THREAD

**Issue by Jaladhjin** [smaitch/Grail#307]
Yeah title ^

Same with like AzerothAutoPilot, Dugi & WoW-Pro

Particularly the section in the Overview stating "designed to provide that quest information to other addons to make their decision processing easier"

**Comment by yoshimo** [comment]
Zygor  had their own dB for quest relations but they removed that long time ago and hardcoded  everything.
Questie also does its own  dB.

**Comment by Emmaleah** [comment]
Wow Pro uses it for 2 things 1)Debugging-especially with quest prereqs 2)Translations to other language versions.

**Comment by smaitch** [comment]
The Grail add is designed to hopefully make this available to any and all who want it, but very few make use of it.  The Wholly addon is a demonstration of some of the things that can be done with the data.  Perhaps in the future some of these databases of information can be combined to make a better quest database addon for more to use.
