### ISSUE TITLE
DF Pre-Patch (10.0) LUA Errors (RETAIL)

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#314]
Broken in Retail as of DF pre-patch (10.0)

LUA Errors as follows:

> Message: Interface/AddOns/Grail/Grail.lua:1472: attempt to call global 'GetFriendshipReputation' (a nil value)
> Time: Wed Oct 26 19:04:12 2022
> Count: 1
> Stack: Interface/AddOns/Grail/Grail.lua:1472: attempt to call global 'GetFriendshipReputation' (a nil value)
> [string "=[C]"]: in function `GetFriendshipReputation'
> [string "@Interface/AddOns/Grail/Grail.lua"]:1472: in function `?'
> [string "@Interface/AddOns/Grail/Grail.lua"]:11821: in function `_Tooltip_OnEvent'
> [string "@Interface/AddOns/Grail/Grail.lua"]:12382: in function <Interface/AddOns/Grail/Grail.lua:12382>
> 
> Locals: 

Also

> Message: Interface/AddOns/Wholly/Wholly.lua:4002: CreateFrame(): Couldn't find inherited node "OptionsButtonTemplate"
> Time: Wed Oct 26 19:04:13 2022
> Count: 1
> Stack: Interface/AddOns/Wholly/Wholly.lua:4002: CreateFrame(): Couldn't find inherited node "OptionsButtonTemplate"
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "@Interface/AddOns/Wholly/Wholly.lua"]:4002: in function `_SetupSearchFrame'
> [string "@Interface/AddOns/Wholly/Wholly.lua"]:753: in function `?'
> [string "@Interface/AddOns/Wholly/Wholly.lua"]:2627: in function `_OnEvent'
> [string "@Interface/AddOns/Wholly/Wholly.lua"]:4559: in function <Interface/AddOns/Wholly/Wholly.lua:4559>
> 
> Locals: 

Also may be some I missed

**Comment by yoshimo** [comment]
```GetFriendshipReputation``` is part of the ```GossipInfo``` space now:
#316
But Wholly seems to need adjustments for the new interface as well :
https://github.com/smaitch/Wholly/issues/51

**Comment by smaitch** [comment]
This should be resolved with the latest versions of the addons.
