### ISSUE TITLE
LUA Errors Still in DF Pre-Patch (Wholly & Grail)

### ISSUE THREAD

**Issue by Wyr3d** [smaitch/Grail#323]
So, iunno if there's a new version in the works already, but since there's no update available as yet, I figured i would reiterate the LUA errors the game is still throwing up in case this is useful:

The first two are Grail LUA errors

No 1

Message: Interface/AddOns/Grail/Grail.lua:1472: attempt to call global 'GetFriendshipReputation' (a nil value)
Time: Mon Nov 21 08:22:32 2022
Count: 1
Stack: Interface/AddOns/Grail/Grail.lua:1472: attempt to call global 'GetFriendshipReputation' (a nil value)
[string "=[C]"]: in function `GetFriendshipReputation'
[string "@Interface/AddOns/Grail/Grail.lua"]:1472: in function `?'
[string "@Interface/AddOns/Grail/Grail.lua"]:11821: in function `_Tooltip_OnEvent'
[string "@Interface/AddOns/Grail/Grail.lua"]:12382: in function <Interface/AddOns/Grail/Grail.lua:12382>

Locals: 

No 2

Message: Interface/AddOns/Wholly/Wholly.lua:4002: CreateFrame(): Couldn't find inherited node "OptionsButtonTemplate"
Time: Mon Nov 21 08:22:34 2022
Count: 1
Stack: Interface/AddOns/Wholly/Wholly.lua:4002: CreateFrame(): Couldn't find inherited node "OptionsButtonTemplate"
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Wholly/Wholly.lua"]:4002: in function `_SetupSearchFrame'
[string "@Interface/AddOns/Wholly/Wholly.lua"]:753: in function `?'
[string "@Interface/AddOns/Wholly/Wholly.lua"]:2627: in function `_OnEvent'
[string "@Interface/AddOns/Wholly/Wholly.lua"]:4559: in function <Interface/AddOns/Wholly/Wholly.lua:4559>

Locals: 

The rest are all xml issue to do with Wholly:

No 3

Message: Interface/AddOns/Wholly/Wholly.xml:545 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

No 4

Message: Interface/AddOns/Wholly/Wholly.xml:553 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

No 5

Message: Interface/AddOns/Wholly/Wholly.xml:561 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

No 6

Message: Interface/AddOns/Wholly/Wholly.xml:569 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

No 7

Message: Interface/AddOns/Wholly/Wholly.xml:577 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

No 8

Message: Interface/AddOns/Wholly/Wholly.xml:585 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

No 9

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/Wholly/Wholly.xml:545 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

No 10

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/Wholly/Wholly.xml:553 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

No 11

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/Wholly/Wholly.xml:561 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

No 12

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/Wholly/Wholly.xml:569 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

No 13

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/Wholly/Wholly.xml:577 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

No 14

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/Wholly/Wholly.xml:585 Couldn't find frame parent: InterfaceOptionsFramePanelContainer
Time: Mon Nov 21 08:22:36 2022
Count: 1

**Comment by smaitch** [comment]
Work is being done on both Wholly and Grail to allow things to work with Dragonflight.  You can download the current work from Github until the release which should be coming out next week.

**Comment by smaitch** [comment]
The latest versions are out and even newer code is added to GitHub.
