### ISSUE TITLE
Errors in pre-patch of Wow

### ISSUE THREAD

**Issue by DreamOfHero** [smaitch/Grail#34]
Hi,

with BfA prepatch in the console appesar this message: "the 093 version or newer of Grail is required" (I've installed 095 version, and Wholly also)

I noticed also that this addon make some ingame errors (6 in total):

1) Message: Interface\AddOns\Grail\Grail.lua:2224: attempt to call local 'GetMapNameByID' (a nil value)
Stack: Interface\AddOns\Grail\Grail.lua:2224: attempt to call local 'GetMapNameByID' (a nil value)
Interface\AddOns\Grail\Grail.lua:2224: in main chunk

2) Message: Interface\AddOns\Grail\Grail-Quests.lua:215: attempt to index global 'Grail' (a nil value)
Stack: Interface\AddOns\Grail\Grail-Quests.lua:215: attempt to index global 'Grail' (a nil value)
Interface\AddOns\Grail\Grail-Quests.lua:215: in main chunk

3) Message: Interface\AddOns\Grail\Grail-NPCs.lua:90: attempt to index global 'Grail' (a nil value)
Stack: Interface\AddOns\Grail\Grail-NPCs.lua:90: attempt to index global 'Grail' (a nil value)
Interface\AddOns\Grail\Grail-NPCs.lua:90: in main chunk

4) Message: Interface\AddOns\Grail\Grail-NPCs-enUS.lua:9: attempt to index global 'Grail' (a nil value)
Stack: Interface\AddOns\Grail\Grail-NPCs-enUS.lua:9: attempt to index global 'Grail' (a nil value)
Interface\AddOns\Grail\Grail-NPCs-enUS.lua:9: in main chunk

5) Message: Interface\AddOns\Grail\Grail-NPCs-itIT.lua:7: attempt to index global 'Grail' (a nil value)
Stack: Interface\AddOns\Grail\Grail-NPCs-itIT.lua:7: attempt to index global 'Grail' (a nil value)
Interface\AddOns\Grail\Grail-NPCs-itIT.lua:7: in main chunk

6) Message: Interface\AddOns\Grail\Grail-BuggedQuests.lua:19: attempt to index global 'Grail' (a nil value)
Stack: Interface\AddOns\Grail\Grail-BuggedQuests.lua:19: attempt to index global 'Grail' (a nil value)
Interface\AddOns\Grail\Grail-BuggedQuests.lua:19: in main chunk

how can I solve and play with this addon on?

Thanks in advance

**Comment by smaitch** [comment]
Most of the basic functionality was returned with the latest two public releases of Wholly and Grail.
