### ISSUE TITLE
Is the addon still maintained or is indeed... :(

### ISSUE THREAD

**Issue by KingDeVeteran** [smaitch/Grail#343]
Over the past couple of months had on and off some Lua errors with either Grail or Wholly

Didn't wrote anything since they appeared to only pop up during certain times, so to say, thus, I never felt annoyed enough about it...

...couple days ago though, going through my addon's list, I noticed that these 2 addons, Grail and Wholly are amongst the few that I have that aren't updated to 10.2 OR haven't been updated in quite a while, sadly :(

Should we still hold onto hop of updates or... 10.0.5 was the last hurrah for the addons?

If errors gonna show up again, gonna start posting them :) thanks for your time and take care ^^

**Comment by smaitch** [comment]
Will hopefully be back to updating over Christmas.

**Comment by KingDeVeteran** [comment]
Awesome :O thanks ^_^

As I've said, if I'll encounter anything from now on, gonna make a new post... hope you're good and have some great holidays ahead :)

**Comment by smaitch** [comment]
Maintenance is happening here and releases are being made also on curseforge.com
