### ISSUE TITLE
Log Season&Expansion

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#347]
C_Seasons.GetActiveSeason & G_WOW PROJECT ID would make sense so we have proper flags for each character log that is submitted and we can tell special realms apart.

There also is GetClassicExpansionLevel()

Combine it with
MAX_EXPANSION_LEVEL_UPDATED
MIN_EXPANSION_LEVEL_UPDATED

**Comment by smaitch** [comment]
I am adding Grail.activeSeason and putting it at the end of the first string used for logging (just past covenant and renown level).

**Comment by yoshimo** [comment]
GetServerExpansionLevel
GetExpansionLevel
Not to forget

**Comment by yoshimo** [comment]
PlayerGetTimerunningSeasonId()  for thinks like the return to Pandaria, so we can weed out changes like questlevels and additional quests to lead you through the zones.

https://warcraft.wiki.gg/wiki/Patch_11.0.0/API_changes
also mentions a few changes for the quest enums and api as the game can filter out quests that have been completed by other characters in your warband already :)
