### ISSUE TITLE
WoW Classic - No Quest names

### ISSUE THREAD

**Issue by Zalaan** [smaitch/Grail#353]
When I open Wholly, there are no quest names. All that shows is "No Name" against each quest. For example "(15) No Name".
When I mouse over it the details of the quest all the information is there, but the quest name is not. This is OK for quests I have completed, but for prerequisites, an quests not started, it is a 'pain' ! 
Any advice to rectify this would be appreciated.
Thank you

**Comment by smaitch** [comment]
In which version of WoW are you playing?  In which language?  What version of Wholly and what version of Grail are you running?

**Comment by Zalaan** [comment]
I am playing WoW Classic (hardcore server) version 1.15.3. Language is English. According to Curseforge installer I am playing Grail-122 and Wholly-090

**Comment by smaitch** [comment]
Thanks.  This should be fixed with https://github.com/smaitch/Grail/commit/7e886a49dcfd1efe75c8acecf422764c051d9c38 which updates the latest Grail found here.
