### ISSUE TITLE
Loremaster quests marked in the wrong area

### ISSUE THREAD

**Issue by Silverscale** [smaitch/Grail#39]
Grail v096
Wholly v067
No other addon active.

While leveling a new character, I'm trying to do the Loremaster achievements for each zone, so I just installed Wholly/Grail to help me do that. But when I checked the option to "Show only Loremaster quests", the quest list emptied. 
After doing some research, I find the quest list in a completely different area, and that prevents the addons to track them correctly.

Right now I'm in Winterspring. Without Loremaster set, it correctly shows the quest list.
![winterspring without loremaster](https://user-images.githubusercontent.com/41900629/43395843-42fae7f4-9408-11e8-9475-297674e1b176.png)

The tooltip however, list the Loremaster zone of these quest as being maraudon 
![winterspring without loremaster tooltip](https://user-images.githubusercontent.com/41900629/43395847-438eb6a0-9408-11e8-86c4-1b6f17252a61.png)

When activating Loremaster, the list empties
![winterspring with loremaster](https://user-images.githubusercontent.com/41900629/43395846-4364f5b8-9408-11e8-8ad1-809291c4873b.png)

But these same quest are shown now at Maraudon
![maraudon with loremaster](https://user-images.githubusercontent.com/41900629/43395844-43202e42-9408-11e8-8f0e-55ffdd39a350.png)

Without Loremaster, the Maraudon quest list is empty (Correctly, i guess. Haven't been there)
![maraudon without loremaster](https://user-images.githubusercontent.com/41900629/43395845-43476246-9408-11e8-8336-0f8504cbc0eb.png)

**Comment by smaitch** [comment]
It turns out the Grail data for Loremaster was not migrated to the new Blizzard map values with the rest of the data.  Once this is done, the Loremster information will be back to what it once was.

**Comment by smaitch** [comment]
The current version of Grail in GitHub should have the Loremaster zones updated to the proper BfA values.

**Comment by smaitch** [comment]
This change was pushed to production.
