### ISSUE TITLE
Problems with Kul Tiran humans

### ISSUE THREAD

**Issue by leobolin** [smaitch/Grail#53]
I don't know why this happens but Grail doesn't work at all on Kul Tiran Humans. Every single quest in the game thinks says I am the wrong race when I'm on a Kul Tiran, so only quests in my log will show up in Wholly. This includes quests flagged to be available for _Any_ race.

There is also a long freeze when logging in that only happens on Kul Tirans. Everything works fine with all other races including Zandalari Trolls and Dark Iron Dwarves.

There are no Lua errors.

**Comment by leobolin** [comment]
I'm pretty sure the issue is with the Kul Tiran bitmap. Pretending to be Human by chainging the bitmap to 0x00008000 makes all Human quests show up and I no longer freeze for several seconds when loading the addon.

**Comment by smaitch** [comment]
Until I get a new release out, if you want to edit the Grail.lua file you can change the line that looks like:
`bitMaskRaceAll			=	0x6fff800f,`
 to the following:
`bitMaskRaceAll			=	0xffff800f,`
 The difference is that first "6" becomes an "f" which should allow both of the two new Allied races to be considered part of "all races".

**Comment by leobolin** [comment]
Cheers!

**Comment by yoshimo** [comment]
Should be fixed with https://github.com/smaitch/Grail/commit/117faac21282af7ba704ccb41179c6000f63d7bd

**Comment by smaitch** [comment]
Grail 100 has been released and has this fix.
