### ISSUE TITLE
Issues on WoW Classic Realms

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#56]
Stress test reveals we are relying on non existing api calls:
GetFriendshipReputation

it also fails at line 2220 in 
			---	[600000]=GetMapNameByID(19)..' '..REQUIREMENTS,
			---	[600001]=GetMapNameByID(19)..' '..FACTION_ALLIANCE..' '..REQUIREMENTS,
			---	[600002]=GetMapNameByID(19)..' '..FACTION_HORDE..' '..REQUIREMENTS,

Hovering over quest windows results in

..\AddOns\Grail\Grail.lua line 8672:
   com_mithrandir_grailTooltip:SetHyperlink(): Unknown link type

**Comment by smaitch** [comment]
I am attempting to make modifications that just ignore features not present in Classic.  The goal is to have one addon that can work in both classic and retail.  The big issue is the TOC.

**Comment by yoshimo** [comment]
The issues are still present. Loading outdated addon works on classic too, so what problem exactly do we have with TOC? If it is just the warning, then packaging a classic version is not a problem as long as the code itself isn't split.

**Comment by smaitch** [comment]
The only issue with TOC is needing to load outdated addons.  I will shortly upload the latest Wholly and Grail to GitHub.  They will work in both Classic and Retail.  I have made some changes that are likely to freak some people out, but at least we can separate the data per environment.

**Comment by smaitch** [comment]
From the basic testing I have done the API is working on Classic.  It is limited by the quest/NPC information present for it, but we can learn that over time.
