### ISSUE TITLE
Update Curseforge to redirect the issue tracker to github

### ISSUE THREAD

**Issue by kernighan** [smaitch/Grail#62]
People are opening issues via the Curseforge issue tracker as well as in GitHub. It would likely be best to point Curse at github so there is only a single issue tracker in use.

**Comment by smaitch** [comment]
I had thought for people to put tickets into GitHub they would have to sign up for GitHub, but in curse forge they do not.  Therefore, I wanted to make it as easy as possible for people to submit issues.  I do attempt to process the tickets even on curseforge, and eventually close them if no one has responded in a long time, or after the next release is out that should have fixed the problem.

**Comment by kernighan** [comment]
Ah, I didn't realize you couldn't do anonymous on github.  I use bitbucket, which allows anonymous issues to be filed.

**Comment by smaitch** [comment]
I have made the redirection for Grail.  I have yet to comb through the old tickets on Curseforge to see which ones need to be made into ones on GitHub.
