### ISSUE TITLE
Updated add-on not seen in Twitch Launcher

### ISSUE THREAD

**Issue by tailcat** [smaitch/Grail#63]
the Twitch launcher is showing 099 as the latest version of Grail, same goes for Wholly (its stuck at 070)

Have had to manually download 100 and 101

<img width="1082" alt="Screen Shot 2019-09-26 at 5 20 12 PM" src="https://user-images.githubusercontent.com/1470609/65733110-fbb72e80-e081-11e9-8a83-73dea4a2184d.png">

**Comment by smaitch** [comment]
I did not realize this.  Thanks for the warning.  Now I have to figure out why this has not been updated properly.

**Comment by smaitch** [comment]
For the latest release I only marked the Retail version and that seems to have made it so Twitch displays the version.  I do not know whether Twitch can be made to show only Classic or a combination of Classic and Retail.  But at least it is showing the latest version.
