### ISSUE TITLE
Classic- Some updates/expansions of NPC/items etc

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#64]
Foe Classic
Here are some updates/expansions of NPC/items etc
I will send some updated/additional quest data soon. Several of the quest related NPCs are in the attached.

[20190927 - NPCs etc.txt](https://github.com/smaitch/Grail/files/3664502/20190927.-.NPCs.etc.txt)

**Comment by smaitch** [comment]
Thanks.  I have integrated this data into the next release of Grail.

**Comment by Nerillida** [comment]
Would you like me to use a fork of the files, rather than having to write it once and you having to rewrite it?
It would be for you to decide on any merges ofc.
