### ISSUE TITLE
20191001 CLASSIC NPCs- Alignments- minor bits

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#66]
Classic - based on your recently updated version of 2-3 days ago.

I attach a file.

Is there another way that you may prefer this data, an easier format, a fork or whatever here?

[20191001 NPCs- Alignments- minor bits.txt](https://github.com/smaitch/Grail/files/3673843/20191001.NPCs-.Alignments-.minor.bits.txt)

**Comment by smaitch** [comment]
In general it is probably easier to make changes in a branch and make a pull request.  That way I can merge changes using GitHub.

These changes are being made in the next Grail.

**Comment by Nerillida** [comment]
Thank you for your speedy response.
It may be me but I can't seem to branch.
I have not used this repository, so it may be me.
Or do you have to allow this?

Thanks again.

![Screen Shot 2019-10-01 at 04 29 32](https://user-images.githubusercontent.com/55858788/65932074-20096700-e404-11e9-828d-e4ed66870774.png)

**Comment by smaitch** [comment]
You should be able to make a branch from the fork that you made.  I imagine you should then be able to make a pull request from that branch.  I have never done it here but that is my understanding.

**Comment by Nerillida** [comment]
I will try that.
