### ISSUE TITLE
   attempt to concatenate local 'soughtParameter' (a nil value)

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#69]
> Date: 2019-10-09 23:08:07
> ID: 2
> Error occured in: Global
> Count: 1
> Message: ..\AddOns\Grail\Grail.lua line 7524:
>    attempt to concatenate local 'soughtParameter' (a nil value)
> Debug:
>    [C]: ?
>    Grail\Grail.lua:7524:
>       Grail\Grail.lua:7473
>    (tail call): ?
>    Grail\Grail.lua:9836: StatusCode()
>    Grail\Grail.lua:4011: ClassificationOfQuestCode()
>    Wholly\Wholly.lua:1507: _ClassifyQuestsInMap()
>    Wholly\Wholly.lua:3326: _RecordTooltipNPCs()
>    Wholly\Wholly.lua:645: ?()
>    Wholly\Wholly.lua:2589: _OnEvent()
>    Wholly\Wholly.lua:4292:
>       Wholly\Wholly.lua:4292

I suspect this has to do with the new allied factions, vulpera and mechagnomes

**Comment by smaitch** [comment]
It means that we have an S or R code in a quest that is not being handled properly because the race is nil (which means it is probably not a supported one in Grail).  Have you added a code for one of these races?  When are those races available?

**Comment by yoshimo** [comment]
8.3.
I havent added anything yet, because i wasnt sure if just continuing the race bitmask with thr next two doubled numbers was enough.

**Comment by smaitch** [comment]
We need to get letters to represent them and then match those letter codes with the bit mask values.  And then get localized names (which I have not even done for the previous ones).  Then we need to update the "all" bit mask.  There are a few things that need to be done.  :-)

**Comment by yoshimo** [comment]
```
Dump: value=UnitRace("player")
[1]="Mechagnom",
[2]="Mechagnome",
[3]=37
```
```
[1]="Vulpera",
[2]="Vulpera",
[3]=35
```

Is there an api for localised gender specific race translations?

**Comment by yoshimo** [comment]
Or better german table:

gender | localised Race in german | english race | race id | faction
-- | -- | -- | -- | --
female | Mechagnom | Mechagnome | 37 | alliance
male | Mechagnom | Mechagnome | 37 | alliance
female | Vulpera | Vulpera | 35 | horde
male | Vulpera | Vulpera | 35 | horde
female | Nachtgeborene | Nightborne | 27 | alliance
male | Nachtgeborener | Nightborne | 27 | alliance
female | Hochbergtauren | HighmountainTauren | 28 | horde
male | Hochbergtauren | HighmountainTauren | 28 | horde
female | Mag'har | MagharOrc | 36 | horde
male | Mag'har | MagharOrc | 36 | horde
female | Zandalaritroll | ZandalariTroll | 31 | horde
male | Zandalaritroll | ZandalariTroll | 31 | horde
female | Lichtgeschmiedete Draenei | LightforgedDraenei | 30 | alliance
male | Lichtgeschmiedeter Draenei | LightforgedDraenei | 30 | alliance
female | Dunkeleisenzwergin | DarkIronDwarf | 34 | alliance
male | Dunkeleisenzwerg | DarkIronDwarf | 34 | alliance
female | Kul Tiranerin | KulTiran | 32 | alliance
male | Kul Tiraner | KulTiran | 32 | alliance
female | Leerenelfe | VoidElf | 29 | alliance
male | Leerenelf | VoidElf | 29 | alliance

**Comment by smaitch** [comment]
Is there a table like this for the other supported languages?

**Comment by yoshimo** [comment]
Maybe, but this one is made manually by myself from scratch.

**Comment by smaitch** [comment]
Ahh, next Grail should now have support for Mechagnome and Vulpera, including those German translations above.

**Comment by smaitch** [comment]
Grail 103 is now released.
