### ISSUE TITLE
CLASSIC - Holiday Quests

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#72]
I have tested with Children's Week  etc "HC" in some quests.  An error

Date: 2019-10-12 08:56:23
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Grail\Grail.lua line 3825:
   attempt to call local 'CalendarGetNumDayEvents' (a nil value)
Debug:
   Grail\Grail.lua:3825: CelebratingHoliday()
   Grail\Grail.lua:7507:
      Grail\Grail.lua:7466
   (tail call): ?
   Grail\Grail.lua:9856: StatusCode()
   Grail\Grail.lua:4016: ClassificationOfQuestCode()
   Wholly\Wholly.lua:1509: _ClassifyQuestsInMap()
   Wholly\Wholly.lua:1949: _ForcePanelMapArea()
   Wholly\Wholly.lua:4280: UpdateQuestCaches()
   Wholly\Wholly.lua:1040: ?()
   Wholly\Wholly.lua:2591: _OnEvent()
   Wholly\Wholly.lua:4296:
      Wholly\Wholly.lua:4296
Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Interface\AddOns\Grail\Grail.lua:8694
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Interface\AddOns\Grail\Grail.lua:6716
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Interface\AddOns\Grail\Grail.lua:9269
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Interface\AddOns\Grail\Grail.lua:3226
 QuestLocationsAccept = <function> defined @Interface\AddOns\Grail\Grail.lua:8852
 IsAvailable = <function> defined @Interface\AddOns\Grail\Grail.lua:6698
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Interface\AddOns\Grail\Grail.lua:6403
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Interface\AddOns\Grail\Grail.lua:6431
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:4872
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Interface\AddOns\Grail\Grail.lua:8071
 _MarkQuestType = <function> defined @Interface\AddOns\Grail\Grail.lua:5232
 receivedCalendarUpdateEventList = false
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Interface\AddOns\Grail\Grail.lua:9023
 _ProcessServerBackup = <function> defined @Interface\AddOns\Grail\Grail.lua:8383
 bitMaskQuestVariableLevel = 4278190080
 MeetsRequirementGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:7668
 _EvaluateCodeAsPrerequisite = <function> defined @Interface\AddOns\Grail\Grail.lua:5746
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Interface\AddOns\Grail\Grail.lua:7753
 DoesNPCExist = <function> defined @Interface\AddOns\Grail\Grail.lua:5711
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Interface\AddOns\Grail\Grail.lua:3519
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Interface\AddOns\Grail\Grail.lua:7936
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Interface\AddOns\Grail\Grail.lua:3054
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Interface\AddOns\Grail\Grail.lua:7253
 _HandleEventAchievementEarned = <function> defined @Interface\AddOns\Grail\Grail.lua:6398
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 16384
 _ReputationExceeds = <function> defined @Interface\AddOns\Grail\Grail.lua:9457
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = false
 LearnObjectName = <function> defined @Interface\AddOns\Grail\Grail.lua:7179
 _ContainsAliasNPC = <function> defined @Interface\AddOns\Grail\Grail.lua:5453
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Interface\AddOns\Grail\Grail.lua:9556
 QuestBreadcrumbs = <function> defined @Interface\AddOns\Grail\Grail.lua:8688
 NPCName = <function> defined @Interface\AddOns\Grail\Grail.lua:7891
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
 UnregisterObserverQuestStatus = <function> defined @Interface\AddOns\Grail\Grail.lua:10103
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 QuestOnAcceptCompletes = <function> defined @Interface\AddOns\Grail\Grail.lua:9035
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 _IntegerFromStringPosition = <function> defined @Interface\AddOns\Grail\Grail.lua:5287
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Interface\AddOns\Grail\Grail.lua:6750
 bitMaskCanGetUnused8 = 4194304
 bitMaskCanGetUnused15 = 1073741824
 MeetsRequirementGroupPossibleToComplete = <function> defined @Interface\AddOns\Grail\Grail.lua:7696
 questReputations = <table> {
 }
 versionNumber = 102
 _ProcessQuestsForHandlers = <fu
AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  auccheapsearcher, v20190917r3
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BadBoy, vv1-classic
  BadBoyCCleaner, vv8.2.0
  BadBoyGuilded, vv8.2.0
  BasicChatMods, vv2-classic
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BetterVendorPrice, vv1.09.01
  ClassicCastbars, vv1.0.6
  ClassicCastbarsOptions, v
  ClassicSpellActivations, v
  ClassTrainerPlus, v0.5-beta
  CTBarMod, v8.2.5.3
  CTBuffMod, v8.2.5.2
  CTCore, v8.2.5.2
  CTLibrary, v8.2.5.1
  CTMailMod, v8.2.0.8
  CTMapMod, v8.2.5.2
  CTPartyBuffs, v8.2.0.1
  CTUnitFrames, v8.2.5.2
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  ExtVendorUIClassic, v1.0.4
  GatherMate2, v1.45.4
  Grail, v102
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v27178
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v29297
  GrailReputationsclassic, v007
  GrailWhen, v002
  GSE, v2.4.21
  GSEGUI, v2.4.21
  GSELDB, v2.4.21
  Informant, v8.2.6374 (SwimmingSeadragon)
  LetMeCast, v1.3
  MageButtons, v1.0
  Mapster, v1.8.5
  Misspelled, v1.7.4
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  OmniCC, v8.2.4
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v4.1.1 BETA
  QuestLogEx, v1.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TFTB, v1.10
  TitanClassic, v1.1.0.11302
  TitanClassicAmmo, v1.1.0.11302
  TitanClassicBag, v1.1.0.11302
  TitanClassicClock, v1.1.0.11302
  TitanClassicGold, v1.1.0.11302
  TitanClassicLocation, v1.1.0.11302
  TitanClassicLootType, v1.1.0.11302
  TitanClassicPerformance, v1.1.0.11302
  TitanClassicRegen, v1.1.0.11302
  TitanClassicRepair, v1.1.0.11302
  TitanClassicVolume, v1.1.0.11302
  TitanClassicXP, v1.1.0.11302
  WhatsTraining, v1.8.4
  Wholly, v074
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=8a0)

I assume we will have the holidays in Classic sometime.

**Comment by smaitch** [comment]
The next release of Grail will no longer throw a Lua error, but we still cannot handle the proper holiday information that is derived from the calendar as there is no calendar in Classic.

**Comment by Nerillida** [comment]
Yes, Kinda guessed that. As a suggestion, a  page on Wholly to mark them on or off? I realise that this is decidedly inelegant.

**Comment by smaitch** [comment]
The latest Grail should handle the lack of holidays in Classic well.  If we start getting holidays in Classic we can add them but will need a new release of Grail each time we add a set of holidays.
