### ISSUE TITLE
Faction markers

### ISSUE THREAD

**Issue by Nerillida** [smaitch/Grail#88]
I recently sent some quests, priest quests. I removed the FA/FH from them as I understood that if the quest giver was faction, that marked the quest appropriately.

I also seem to have read that you were moving to lowercase "f" on quests to distinguish those in genuine need of faction forcing at the quest level.

In anticipation of similar with my other class/level research, can you please explain what I missed.

Thanks.

**Comment by smaitch** [comment]
If the quest giver is marked for a faction that will allow the quest to show properly for that faction.  Also, if the quest is marked with a faction the same applies.  The automatic process that reads the Blizzard faction information will add/remove factions as appropriate from the Blizzard data.  In this case the automatic process marks them as faction specific.
In general, we should not mark factions on quests and leave those that are marked (unless they are incorrect).  We should mark factions on NPCs.
If there is a case, for example, when we have a quest giver who is good for both factions, but the quest is specific to one faction, and the automatic process does not have a faction marked, we should mark the quest with a fA or fH code appropriately.

**Comment by Nerillida** [comment]
That's what I thought, but there was a quest with no faction marker, with a quest giver with a faction marker, and you  added a quest factionFA/FH.
I just don't get why.

G[5627]='FA K0100 L010 N255 RE CT A:11401 T:11401 I:5628,5629,5630,5631,5632,5633 E31727'

as an example, you added FA just before the latest release

A:11401 = G[11401]={'FA 1457:39.50,81.17'} -- Priestess Alathea

That and a few similar. I am still not understanding. Sorry.

**Comment by smaitch** [comment]
The only reason why it was added was because the automatic process did so.  If I did not add it this time, when the automatic process is run again, it will add it then.
The fact that the quest and the NPC are marked with the same faction is not a problem.  If they were different then there would be a problem.

**Comment by Nerillida** [comment]
Ah, thanks, I thought that I had missed something.
