### ISSUE TITLE
Grail causes constant lag

### ISSUE THREAD

**Issue by Storm-Engineer** [smaitch/Grail#97]
I just tried out Wholly which needed Grail, and ran right into this issue.

When Grail is enabled (even with Wholly disabled) every time certain actions are performed, eg. looting a container or corpse, the game will freeze up for 1-2 seconds.

Disabled every other addon and the issue still persisted.

**Comment by smaitch** [comment]
In the newer zones (that have treasures), Grail determines that a treasure is opened by checking which quests are completed after looting.  Unfortunately this happens with looting things that are not treasures as well.  You can control whether Grail does this with the slash command:

/grail loot

This will toggle the feature on/off.  When it is off your lag should go away, but it means that Grail cannot tell that you have found treasure chests.

**Comment by Storm-Engineer** [comment]
I see. So WoW internally treats once-per-character treasure chests as quests?

I have noticed a bit of lag with treasure chests (and those only) already in the past, and I have some other addons tracking treasures, so perhaps there is a way to do this without checking every time anything is looted?

**Comment by smaitch** [comment]
For determining whether a treasure chest has been looted I have only found that checking which quests have been newly completed works.  If there were another way I would love to know what it is since dealing with the looting system is such an ugly hack.

**Comment by Storm-Engineer** [comment]
Hmm, there are two places where you can can look maybe. One is the addon RareScanner (https://www.curseforge.com/wow/addons/rarescanner), which also tracks treasure chests and if they were opened. It seems though that rarely it doesn't mark them opened and I have to do it manually.

The other is HandyNotes (https://www.curseforge.com/wow/addons/handynotes). There are several sub-addons (eg https://www.curseforge.com/wow/addons/handynotes_legiontreasures) for it containing lists for treasures and chests, that will remove the map marker once the corresponding container is looted. This one always worked 100% for me.

Neither of these seemed to cause any lag. Maybe you can look into them or contact the creators?

**Comment by emersonrp** [comment]
Finally trial-and-errored my way into discovering Grail was what was causing my loot lag.  I realize this ticket is months old, but just another vote that if there's some way Grail could avoid freezing the game every time something is looted, it would let me start using it again, which would be awesome.

**Comment by smaitch** [comment]
The latest version of Grail on GitHub has changes in it that should make looting faster.

**Comment by emersonrp** [comment]
Very nice, yes at least for me, the github version has no perceptible lag at all when looting.  Awesome, thanks!
